### ISSUE TITLE
Enhancement proposal: smartparens pairs

### ISSUE THREAD

**Issue by Gastove** [fsharp/emacs-fsharp-mode#100]
I love [smartparens](https://github.com/Fuco1/smartparens) to pieces. In my own emacs configs, I've added sets of F#-specific pairs, so that, for instance, typing pipe inside `[]` gets you `[||]` (and likewise pipe inside `()` gets you banana clips), and typing `@` inside `<>` gets you `<@@>` (or `<@@@@>` with an extra press). 

I'd be happy to add this in to `fsharp-mode`, but it will entail adding a dependency on `smartparens`. Thoughts?

**Comment by juergenhoetzel** [comment]
> I'd be happy to add this in to fsharp-mode, but it will entail adding a dependency on smartparens. Thoughts?

Shouldn't this be added to [smartparens](https://github.com/Fuco1/smartparens): Like the other modes [smartparens](https://github.com/Fuco1/smartparens) supports? The functionality shouldn't depend on *fsharp-mode*?

**Comment by Gastove** [comment]
@juergenhoetzel Ah, good point. I find `smartparens` so nice that I wouldn't want to code without it, but on further review: all the modes I thought of as providing very nice SP configurations are actually using configs from SP itself and suggesting that users turn `smartparens` on. Works for me.

**Comment by juergenhoetzel** [comment]
@Gastove  I'm very keen to see your *F#* pull request for [smartparens](https://github.com/Fuco1/smartparens)
because I currently migrate my *Emacs* setup from  *paredit* to *smartparens*

**Comment by Gastove** [comment]
@juergenhoetzel great! I'll try and get that together, then; I'll re-open this issue until I can post the `smartparens`, then I'll close this issue.

**Comment by Fuco1** [comment]
I'd be happy to grant you people contributor access so you can maintain the code for this without going through me all the time (as I know near to nothing about ML or fsharp).  A pull request is always welcome but the reviews can be just between you (all I need is that you add tests and don't break stuff :D)

**Comment by juergenhoetzel** [comment]
@Gastove IMO this issue can be closed now.

@Fuco1 Thanks for your confidence and creating `smartparens`
