### ISSUE TITLE
How to disable autocomplete drop down in comments?

### ISSUE THREAD

**Issue by michelrandahl** [fsharp/emacs-fsharp-mode#101]
_Forgive me if this is the wrong place to ask questions, I am still trying to get used to github and I don't see other places to ask questions on projects than in the issues (which I personally feel should be related to bugs, and not questions)..._

Since I updated all my emacs plugins recently, I am now getting autocompletion drop downs when writing in F# comments.
I didn't get autocompletion dropdowns in comments before updating, and I find them to be profoundly annoying since they hide my code while I'm writing on a comment. Don't get me wrong, I love having the autocompletion dropdown when working with the actual code itself, -I just don't want them when writing on my comments as they obscure the view of the code.

**Is there a way to get rid of autocompletion dropdowns when writing on comments?**

_I realize that the "autocompletion in comments" might be caused by another plugin since I am using Spacemacs which is bundled with many plugins, but as a clueless Emacs rookie I have to start the investigation somewhere..._

**Comment by nosami** [comment]
Seems like you are hitting `dabbrev` completions (words that can be anywhere in the buffer).

The way the F# emacs plugin has been setup, it tries to use real intellisense first, then falls back to any other available `company-mode` (the completion engine) backends.

`(setq company-backends (list 'fsharp-ac/company-backend))` would force `company-mode` to only use real intellisense.

**Comment by nosami** [comment]
The problem with ^^ is that that would clobber the company-backends for all file types. If you want to remove word completions from all file types then this might work for you (untested)

```elisp
  (setq company-backends
         (let ((backends-to-remove '(company-dabbrev company-dabbrev-code company-keywords)))
               (remove-all #'(lambda (backend) (member backend backends-to-remove)) company-backends)))

(defun remove-all (predic seq &optional res)
   "Remove items that could be anywhere inside a nested list"
   (if (null seq)
       (reverse res)
       (cond ((and (not (null (car seq))) (listp (car seq)))
              (remove-all predic (cdr seq)
                          (cons (remove-all predic (car seq)) res)))
             ((funcall predic (car seq))
              (remove-all predic (cdr seq) res))
             (t (remove-all predic (cdr seq) (cons (car seq) res))))))
 ```

**Comment by michelrandahl** [comment]
Thank you so much!
Using `(setq company-backends (list 'fsharp-ac/company-backend))`  is very satisfying for me for now, since I currently only work with F# projects.

_Since I am writing here, I might as well also send out a big thanks to you guys for making this plugin, which I have happily been using it for more than half a year now in Linux :+1: _

**Comment by juergenhoetzel** [comment]
Also see: https://github.com/fsharp/emacs-fsharp-mode/issues/102#issuecomment-254626653

I guess I finally found a solution: https://github.com/fsharp/emacs-fsharp-mode/pull/104
