### ISSUE TITLE
File not part of loaded project, even though correct project was loaded

### ISSUE THREAD

**Issue by krgn** [fsharp/emacs-fsharp-mode#106]
### Description

When loading a project file using `C-c C-p` certain files from my project are still not recognized as part of the loaded project. This is a really strange issue, as it seems to only affect certain files, not others. Completion and Flycheck errors are not available in those files. 

### Repro steps

1. Open project file
2. Navigate to a file 
3. Use company completion

### Expected behavior

Completion and error checking with flycheck should work on all files of a fsproj.

### Actual behavior

Neither completion nor flycheck errors work on some files of the fsproj.

### Known workarounds

I have no workaround for this so far.

### Related information 

* NixOS GNU/Linux
* Emacs 25.1.1
* Mono Stable 4.6.0.182/3ed2bba

**Comment by rneatherway** [comment]
What is the value of `fsharp-ac--project-files` (you can use `C-h v`)?

**Comment by krgn** [comment]
Its strange, it contains `.fsproj` and `.fs` entries:

```
("/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Web/Frontend/Main.fs"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Frontend.fsproj"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Web/Views/Patches.fs"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Frontend.fsproj"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Web/Core/Keyboard.fs"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Frontend.fsproj"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Web/Core/Client.fs"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Frontend.fsproj"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Web/Core/Worker.fs"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Frontend.fsproj"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Web/Core/ViewController.fs"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Frontend.fsproj"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Web/Core/Plugin.fs"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Frontend.fsproj"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Web/Core/Html.fs"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Frontend.fsproj"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Web/Core/Crypto.fs"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Frontend.fsproj"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Web/Core/Browser.fs"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Frontend.fsproj"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Core/ClientMessage.fs"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Frontend.fsproj"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Core/StateMachine.fs"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Frontend.fsproj"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Core/CueList.fs"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Frontend.fsproj"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Core/Cue.fs"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Frontend.fsproj"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Core/Patch.fs"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Frontend.fsproj"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Core/IOBox.fs"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Frontend.fsproj"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Raft/Node.fs"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Frontend.fsproj"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Core/LogLevel.fs"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Frontend.fsproj"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Core/Util.fs"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Frontend.fsproj"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Core/Color.fs"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Frontend.fsproj"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Core/Session.fs"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Frontend.fsproj"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Core/User.fs"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Frontend.fsproj"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Core/Aliases.fs"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Frontend.fsproj"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Core/IpAddress.fs"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Frontend.fsproj"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Core/Id.fs"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Frontend.fsproj"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Core/Error.fs"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Frontend.fsproj"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Core/Serialization.fs"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Frontend.fsproj"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Web/Core/FlatBufferTypes.fs"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Frontend.fsproj"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Core/FlatBuffers.fs"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Frontend.fsproj"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/AssemblyInfo/FrontendInfo.fs"
"/home/k/src/projects/iris/iris/dotnet/src/Iris/Frontend.fsproj")
```

**Comment by krgn** [comment]
But, actually not the `.fsproj` that I loaded! 

So, apparently the exact sequence of events is the following:

1. open some files in the project
2. `fsharp-mode` picks the first `.fsproj` it finds (Frontent.fsproj)
3. I use `C-c C-p` to load Service.fsproj

These three steps lead up to this value in `fsharp-ac--project-files`. Does that make sense?

**Comment by krgn** [comment]
When I quit the process, and re-load Service.fsproj the variable stays empty. At that point it seems that the process cannot be started anymore at all. 

My version of `fsharp-mode` is:  20160719.315

**Comment by rneatherway** [comment]
It's a map from F# files to the fsproj they are part of. I can see entries for `"/home/k/src/projects/iris/iris/dotnet/src/Iris/Frontend.fsproj"`, isn't that the one you loaded?

**Comment by krgn** [comment]
This is loaded automatically whenever I open any file in this project, presumably because the project files are enumerated in alphabetic order (correct?). 
When I load a different project file (in my case a file called Service.fsproj), it does not appear in that list. Some files from that project get syntax-checked fine (maybe the list of intersecting files with the previously loaded project, Frontend.fsproj?) and some are not.

**Comment by rneatherway** [comment]
Ah, you have projects with overlapping sets of files? That isn't supported. The thing is, what context would you expect the file to be type-checked in?

**Comment by krgn** [comment]
Yes, I have overlapping sets of files because I'm developing code targeting Fable and .NET side-by-side. If I want to switch to a different project file, then I should just use `C-c C-q` to quit, and `C-c C-p` to load the new project correct?

**Comment by rneatherway** [comment]
Yes, I'm afraid that is the best we can do at the moment. It seems like maybe that is not working for you? I just tried it here and it seems OK.

**Comment by krgn** [comment]
No, true, that oddly does not work correctly. After shutting down the process and restarting with the new project, the variable is empty. Should I create a new issue for this?

**Comment by krgn** [comment]
Or, I could rename this one as well.

**Comment by rneatherway** [comment]
Either way is fine by me. To debug please:

1. start a fresh Emacs
2. `(setq fsharp-ac-debug 2)`
3. Reproduce the issue
4. Paste the contents of the buffer `*fsharp-debug*` here.

**Comment by krgn** [comment]
Ok, here it goes. When I try to open `Service.fsproj` I get the following exception. The `*fsharp-debug*` buffers stays completely empty (that said, it filled up with about 2MB of data before when it loads the default project, making Emacs really hard to use :)).

```
Quitting fsharp completion process
/home/k/src/projects/iris/iris/dotnet/src/Iris/Service.fsproj:
Microsoft.Build.Exceptions.InvalidProjectFileException: /home/k/src/projects/iris/iris/dotnet/src/Iris/Service.fsproj: Invalid path
  at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.Program+FSharpProjectFileInfo..ctor (System.String fsprojFileName, Microsoft.FSharp.Core.FSharpOption`1[T] properties, Microsoft.FSharp.Core.FSharpOption`1[T] enableLogging) [0x0012a] in <5707a31a06d737baa74503831aa30757>:0 
  at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.Program.getOptions@376 (System.Boolean enableLogging, Microsoft.FSharp.Collections.FSharpList`1[T] properties, System.String file) [0x0000f] in <5707a31a06d737baa74503831aa30757>:0 
  at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.Program.getOptions (System.String file, System.Boolean enableLogging, Microsoft.FSharp.Collections.FSharpList`1[T] properties) [0x00005] in <5707a31a06d737baa74503831aa30757>:0 
  at Microsoft.FSharp.Compiler.SourceCodeServices.ProjectCrackerTool.Program.main (System.String[] argv) [0x000b8] in <5707a31a06d737baa74503831aa30757>:0 
```

**Comment by rneatherway** [comment]
Obvious question: what, if anything, is at that path?

**Comment by krgn** [comment]
My project file :)

**Comment by krgn** [comment]
Could it be that something is invalid in the project file? xbuild/fsc does not tell me anything of the sort, but it could be that ProjectCracker finds something it can't parse/handle?

**Comment by rneatherway** [comment]
Very possible, could you try running it manually as described at https://github.com/fsharp/emacs-fsharp-mode/#project-file-issues please

**Comment by krgn** [comment]
No error, unfortunately. Should I paste the output somewhere?

**Comment by krgn** [comment]
I replaces the `Service.fsproj` with a copy of one that works, so it must have had to do something the file. No idea what it could be.

**Comment by rneatherway** [comment]
Do you still have the "broken" one? if it happens again then a diff might be interesting. I'll close the issue for now, but please reopen if it reoccurs.

**Comment by krgn** [comment]
I have a diff, but there is nothing in there that looks suspicious. The only thing I noticed that those files have a BOM, which under different circumstances have lead to problems for me. Could that be a hint?

**Comment by rneatherway** [comment]
The BOM should be fine for MSBuild, and really the project cracker just passes it along, so I am at a bit of a loss I'm afraid.

**Comment by krgn** [comment]
Fair enough. Thank you for you help! At least now I understand how I can debug these things in the future!

**Comment by rneatherway** [comment]
:-)
