### ISSUE TITLE
fsharp-mode and evil-mode indentation issue

### ISSUE THREAD

**Issue by krgn** [fsharp/emacs-fsharp-mode#107]
### Description

When using `fsharp-mode` together with `evil-mode`, indentation of regions ceases to work correctly, even (and especially) in other modes, such as `emacs-lisp-mode`. This happens *after* the first time `fsharp-mode` was loaded, and from there on appears to be a global issue.

### Repro steps

Steps to reproduce (assuming an unconfigured setup):

- install latest `evil` from melpa 
- install latest `fsharp-mode` from melpa
- start `evil` with `(evil-mode 1)`
- paste the following into the scratch buffer:
```
(defun bla ()
    (interactive)
    (setq bla
        '("hello"
  "hlaksdjf")))
```
- select the function and type `=` to indent it
- open another buffer in `fsharp-mode`, possibly pasting the following (not really needed) 
```
let bla = 42
```
- in `*scratch*` buffer, undo changes using `u`, re-select the defun and type `=` again to indent the code block

### Expected behavior

Typing `=` should indent `emacs-lisp-mode` code (and others) correctly.

### Actual behavior

No indentation of the selected regions happens at all.

### Known workarounds

No workarounds are known at this point.

### Related information 

* Nixos GNU/Linux
* fsharp-mode-20160719.315
* Emacs 25.1.1

**Comment by krgn** [comment]
I looked through the code, and tried fiddling with the options described in `fsharp-mode-indent.el` in a bare setup with no other configuration and only `evil` and `fsharp-mode` installed, but didn't get anywhere. Also, looking at the indentation code this doesn't seem to be doing anything special there, so I wonder whether this might be an `evil` issue.

**Comment by juergenhoetzel** [comment]
I can confirm this issue. *fsharp-mode* changes the *global* `indent-region-function`. This should be fixed by pull request https://github.com/fsharp/emacs-fsharp-mode/pull/110 (by making this a buffer-local variable)

**Comment by krgn** [comment]
@juergenhoetzel you're a hero! :+1:

**Comment by rneatherway** [comment]
Great stuff @juergenhoetzel. Thanks
