### ISSUE TITLE
Popup suggestions not working

### ISSUE THREAD

**Issue by abhi18av** [fsharp/emacs-fsharp-mode#115]
I've installed FSharp packages in my emacs distribution but it's not functioning as it's supposed to. The ideas setup behaviour would be [the popup suggestions working like so.](http://blog.nikosbaxevanis.com/2015/04/25/fsharp-on-emacs-with-spacemacs/)

I've tried out various combinations using the instructions outlined here in the [official F# emacs repo](https://github.com/fsharp/emacs-fsharp-mode) but the variables themselves seem to be missing. Please let me know if it is an error on my part.

**Comment by rneatherway** [comment]
How did you install it? I recommend using MELPA.

**Comment by abhi18av** [comment]
Actually I'm using the Spacemacs distribution so I just need to add the layer `fsharp` and it's installed from the upstream source `melpa` in this case? Btw, does it explicitely rely on `auto-complete ac` package or it works fine with `company-mode` as well?

Sorry if this is a silly question, bit of a n00b :)

**Comment by rneatherway** [comment]
It used to use auto-complete, but now we switched to company-mode. Can you give some more details about what is going wrong? Does it load the fsharp major mode at least?

**Comment by abhi18av** [comment]
Yes, the major mode, inf-shell and syntax highlighting are working just that `ac/start-process` etc isn't working at all. 

It's kind of tough to discover he methods and classes this way.

**Comment by nosami** [comment]
Adding the fsharp layer to Spacemacs is usually enough to make it work.
I'll test the latest version tomorrow evening.

**Comment by abhi18av** [comment]
Okay, looking forward to a solution. Can't wait to get going with F#

**Comment by abhi18av** [comment]
@nosami , Hey so did you figure out anything over the weekend?

**Comment by nosami** [comment]
Sorry, I forgot. I just tried fsharp-mode-20161103.300 now though. Working fine here.
<img width="793" alt="screen shot 2016-11-15 at 12 20 09" src="https://cloud.githubusercontent.com/assets/667194/20305546/f54f868c-ab2d-11e6-8cc0-7aaefc4fda0d.png">

**Comment by abhi18av** [comment]
Oh, so the path might be wrong. I just installed the `mono-develop` to get going. 

Anyway, `spacemacs` gives the following messages as soon as the file is loaded

```
Error while checking syntax automatically: (error "Buffer trial1.fs has no process") [3 times]
Error: background intellisense process not running.
Quit

```

**Comment by abhi18av** [comment]
This is after I reinstalled the `fsharp` layer

**Comment by nosami** [comment]
Any useful information in the `*Messages*` buffer that might help?

**Comment by abhi18av** [comment]
This might be useful

`[No matches]
Error: /Users/eklavya/Projects/bitworld/FSharp/trial1.fs is not part of the loaded projects. `

How do you setup a basic project? I'm just using a single file `trial1.fs` as a scratchpad

**Comment by nosami** [comment]
Ah, you need an `fsproj` file to work with `.fs` files. You could try using [Forge](https://github.com/fsharp-editing/Forge) to generate a skeleton project.

Alternatively, if you just want a scratchpad to work in, try creating a `.fsx` file (script) instead of a `.fs` file.

**Comment by abhi18av** [comment]
Annnddd it working!! 

Thanks for both the suggestions ;)

I didn't know about either one and strangely it wasn't mentioned in any of the blog posts etc, I'll write up something to help others get going with this tool 

Thanks @nosami , I appreciate your time 👍
