### ISSUE TITLE
Auto-completion for fsx files stops working

### ISSUE THREAD

**Issue by jkaye2012** [fsharp/emacs-fsharp-mode#126]
Hey there,

I'm experience a strange issue with .fsx files and auto-completion. I'm not 100% sure how to reproduce this issue, but whenever I open a new fsx file in Emacs (one that did not exist before), auto-complete stops working for ALL fsx buffers. Similarly, when working in an fsx buffer (with auto-complete working), if I delete all text from the buffer, the same issue seems to occur. So it seems like the scenario that triggers this is an empty fsx buffer being loaded. Any idea what could be causing this?

I'm running on OSX using the Spacemacs fsharp layer. F# 4.1.

**Comment by jkaye2012** [comment]
Some output in the messages buffer when this occurs as well:

```Company: An error occurred in post-command
Company: backend fsharp-ac/company-backend error "Wrong type argument: number-or-marker-p, nil with args (prefix)```

**Comment by rneatherway** [comment]
Hi, perhaps an issue with F# 4.1, I am not sure. Could you gather some debug log output and paste it here please? https://github.com/fsharp/emacs-fsharp-mode/#troubleshooting

**Comment by rneatherway** [comment]
Closing as dormant
