### ISSUE TITLE
Malformed JSON "non-IL or abstract method with non-zero RVA"

### ISSUE THREAD

**Issue by fbie** [fsharp/emacs-fsharp-mode#130]
Completion and tool tip does not work at all and instead this error message is produced:

```
Error: F# completion process produced malformed JSON (non-IL or abstract method with non-zero RVA).
error in process filter: fsharp-ac-filter-output: Wrong type argument: hash-table-p, "Error: F# completion process produced malformed JSON (non-IL or abstract method with non-zero RVA)."
```

This happens every time when I move the cursor to any symbol in the open buffer. I am running GNU Emacs 26.0.50 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.18.9) of 2017-05-16 and Mono:

```
$ mono -V
Mono JIT compiler version 5.0.0 (Stable 5.0.0.100/9667aa6 Thu May 11 14:48:10 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)
```

**Comment by rneatherway** [comment]
What version of fsharp-mode and how did you install?

**Comment by fbie** [comment]
fsharp-mode version is 20170416.335, I installed via MELPA and use-package.

**Comment by rneatherway** [comment]
Thanks, please can you try one or both of:

1. Troubleshooting instructions at https://github.com/fsharp/emacs-fsharp-mode#fsharp-ac-debug
2. Running the fsautocomplete.exe binary directly and seeing if that gives more information. I haven't tested with mono 5.0, so perhaps there is a bug in it.

**Comment by nosami** [comment]
I've seen these messages in the console when running F# apps `non-IL or abstract method with non-zero RVA`. Not sure what's causing it yet, but I think you are going to need to filter those out from stdout

**Comment by rneatherway** [comment]
Mono 5.0 is printing those to stdout?? How terrible.

**Comment by nosami** [comment]
Yes. Looks like the message is coming from the compiler somehow https://github.com/fsharp/fsharp/blob/5a942daf930d7023c78f578ec6876b86a6f13f1e/src/absil/ilread.fs#L2358

**Comment by oivvio** [comment]
@fbie Did you find I workaround. I'm getting the same message. I'm also under mono 5.0 since 4.8.1 isn't available for my distro anymore.

**Comment by rneatherway** [comment]
What we need to do, as we can't fix the compiler that quickly, is to ignore
non-JSON lines. I think the easiest way would be for the parsing method to
delete lines that don't start with {. That's here:
https://github.com/fsharp/emacs-fsharp-mode/blob/master/fsharp-mode-completion.el#L637

I plan to do it, but I haven't had time yet.

**Comment by oivvio** [comment]
@rneatherway Thanks. I'll monitor this thread for further developments and use vs code en the meanwhile.

**Comment by juergenhoetzel** [comment]
> @rneatherway Thanks. I'll monitor this thread for further developments and use vs code en the meanwhile.

[PR Don't panic on malformed JSON (debug messages) ](https://github.com/fsharp/emacs-fsharp-mode/pull/131) fixes the issue for me.

By the way: IMO *F#* log debug-messages should go to *stderr* instead of *stdout* to prevent mixing up with normal programm output
