### ISSUE TITLE
use of conventionally reserved key bindings

### ISSUE THREAD

**Issue by retroj** [fsharp/emacs-fsharp-mode#135]
Hello,

Fsharp-mode's bindings for `C-c l` and `C-c r` are against established Emacs convention of reserving letter bindings in the C-c map for users.

https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html

These are conventions worth keeping as they ensure consistency across Emacs.

Thank you for fsharp-mode.

**Comment by rneatherway** [comment]
I would be happy to accept a PR to change them.

**Comment by retroj** [comment]
What shall we change them to?  Python-mode uses `C-c <` and `C-c >` for this same feature.

**Comment by rneatherway** [comment]
Sounds fine to me. @juergenhoetzel do you have any opinion? I don't use that feature.

**Comment by juergenhoetzel** [comment]
> Sounds fine to me. @juergenhoetzel do you have any opinion? I don't use that feature.

LGTM :+1:
