### ISSUE TITLE
Is there a way to disable all functionality (including flycheck) that relies on background processes?

### ISSUE THREAD

**Issue by preetpalS** [fsharp/emacs-fsharp-mode#138]
### Description

Basically I just want syntax highlighting and indentation without any other interactivity that relies on background processes.

### Expected behavior

Ideally you would set a variable and disable all interactivity (no flycheck, no automatic background process related errors on hovering over anything).

### Actual behavior

Even if you have `fsharp-ac-intellisense-enabled` set to nil, you will constantly get the error "Error: background intellisense process not running".

### Known workarounds

None that I know of.

**Comment by rneatherway** [comment]
There currently isn't such a way. The variable you mention is a sensible place to do it, by adding an `if` here: https://github.com/fsharp/emacs-fsharp-mode/blob/master/fsharp-mode.el#L272

**Comment by rneatherway** [comment]
Fixed by #139
