### ISSUE TITLE
Flycheck Errors

### ISSUE THREAD

**Issue by Gastove** [fsharp/emacs-fsharp-mode#141]
### Description

As flycheck attempts to check my F# code, it throws, over and over, variations on this error:

```
error in process filter: Wrong type argument: flycheck-error-p, [cl-struct-flycheck-error #<buffer dow.fsx> fsharp-fsautocomplete "/Users/rossdonaldson/bin/dow.fsx" 10 1 "The value, namespace, type or module 'fsi' is not defined. Maybe you want one of the following:
   fst" error nil]
```
Seems like flycheck is being passed a struct representing an error, rather than an error itself. 

Flycheck version: 31Snapshot
F# Mode version: 20170617.1330

### Repro steps

For me, I can repro this like so:

1. Open any `fsharp-mode` buffer

2. The error is always there

### Known workarounds

I haven't been able to find one yet :/ 

### Related information 

* OSX 10.12
* Current `fsharp-mode` from Melpa (version 20170617.1330 at time of writing)
* Emacs version: 25.2.1
* .NET Runtime, CoreCLR or Mono Version: Mono 5.0.1

**Comment by Gastove** [comment]
....ooookay. I've finally had more time to dig in to this, and it looks like `cl-struct-flycheck-error` is defined by Flycheck itself. So this.... doesn't... make any sense. Especially as I use flycheck basically everywhere, but F# mode is the only place I see this problem.

Gah. Gonna keep digging. Not at all sure what's up yet.

**Comment by juergenhoetzel** [comment]
@Gastove  The signature of `flycheck-error` changed recently: [Add the ability to group related errors](https://github.com/flycheck/flycheck/commit/321fc90d1dc597d8b5e18011ad258179c9d8eb03).

It seems `fsharp-mode` was compiled with a different version of `flycheck`: I get the additional `group field` when using `flycheck-error-new-at`. Could you try to *byte-compile/reinstall* `fsharp-mode` again?

**Comment by Gastove** [comment]
Ooooh, intriguing! Yes, will do!

**Comment by Gastove** [comment]
@juergenhoetzel that was it. Thanks very much! Looking over my other installed packages, I think it's just a coincidence that the others I use frequently, which also use Flycheck, also recently had updates.

**Comment by rneatherway** [comment]
Glad to hear that is solved. I have had problems like that in the past with other packages. Bringing everything up to date normally fixes it.
