### ISSUE TITLE
Errors in fsharp-mode-20170915.933

### ISSUE THREAD

**Issue by krgn** [fsharp/emacs-fsharp-mode#145]
### Description

With current `fsharp-mode-20170915.933` starting `FSAC` produces the following errors:

```
error in process filter: apply: Wrong type argument: stringp, #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("Code" 1 "Message" "File '/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Service/Main.fs' not parsed" "AdditionalData" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ())))
error in process filter: Wrong type argument: stringp, #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ("Code" 1 "Message" "File '/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Service/Main.fs' not parsed" "AdditionalData" #s(hash-table size 65 test equal rehash-size 1.5 rehash-threshold 0.8 data ())))
```

with `fsharp-ac-debug` set to `2`, the following output is produced in the `*fsharp-debug*` buffer:

```
09:55:06.615569: tooltip "/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Service/Main.fs" "    validateOptions parsed" 36 19 400 
09:55:06.630977: {"Kind":"error","Data":{"Code":1,"Message":"File '/home/k/src/projects/iris/iris/dotnet/src/Iris/Iris/Service/Main.fs' not parsed","AdditionalData":{}}}
09:55:06.631097: Received ’error’ message of length 2
```

Completion nor highlighting works for me. 

### Repro steps

1.) Clone [the test respository here](https://github.com/krgn/dotnet-test)
2.) Open `src/Program.fs` and start the ac process
3.) force complete a symbol

### Expected behavior

It should complete the symbol.

### Actual behavior

The minibuffer displays the errors pasted above.

### Known workarounds

No known workarounds exist.

### Related information 

* Nixos 17.03
* fsharp-mode-20170915.933
* Emacs 25.3.1
* mono 5.2.0.215, dotnet 2.0

**Comment by rneatherway** [comment]
I have opened a PR that fixes error message parsing: https://github.com/fsharp/emacs-fsharp-mode/pull/146

That should fix the first problem you are having. After that I get 'The project is not restored' and `dotnet restore` segfaults on my machine. Perhaps you could update your test project with something that is already restored?

**Comment by krgn** [comment]
Yep, that fixes the issue for me! Thanks!

Btw, I tried to start it with that test project from #144 and it appears that the path issue may be gone. Has anything changed in that direction?

Thanks for your quick answer and keeping me productive!

**Comment by krgn** [comment]
But using a little it looks like there might be some more places where the `(gethash ..)` call is missing.

**Comment by krgn** [comment]
Sorry for the noise, I realized that I had some byte compiled `.elc` lying around which caused this confusion. All good!

**Comment by rneatherway** [comment]
Great! Should be available from MELPA soon.
