### ISSUE TITLE
Error when open *.fs file 

### ISSUE THREAD

**Issue by mzabolotko** [fsharp/emacs-fsharp-mode#148]
### Description
I got an error "(wrong-type-argument stringp nil)" when open *.fs file in any directory.
Debugger output
```
  #[257 "\301\300^B\"\203^P^@\302\303\304\305^D#\302Q\207\207" ["[\\\"]\\| " string-match "\"" replace-regexp-in-string "[\\\"]" "\\\\\\&"] 6 "\n\n(fn STR)"](nil)
  mapconcat(#[257 "\301\300^B\"\203^P^@\302\303\304\305^D#\302Q\207\207" ["[\\\"]\\| " string-match "\"" replace-regexp-in-string "[\\\"]" "\\\\\\&"] 6 "\n\n(fn STR)"] (nil "/nologo" "d:/test/sample/sample.sln") " ")
  combine-and-quote-strings((nil "/nologo" "d:/test/sample/sample.sln"))
  fsharp-mode-choose-compile-command("d:/test/sample/Library1.fs")
  fsharp-mode()
  set-auto-mode-0(fsharp-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer Library1.fs> "d:/test/sample/Library1.fs" nil nil "d:/test/sample/Library1.fs" (281474976900952 4133428259))
  find-file-noselect("d:/test/sample/Library1.fs" nil nil nil)
  find-file("d:/test/sample/Library1.fs")
  dired-find-file()
  funcall-interactively(dired-find-file)
  call-interactively(dired-find-file nil nil)
  command-execute(dired-find-file)
```
### Repro steps

1. Create a F# Visual Studio solution with a F# library project.
2. Open Emacs
3. eval (setq debug-on-error t) in *scratch* buffer.
4. Go to solution directory using Dired.
5. Open any *.fs file.

### Expected behavior

The *.fs file should be opened and intellisense should work.

### Actual behavior

Only code syntax highlighting works well.

### Known workarounds
:(

### Related information 
* Windows 10 
* GNU Emacs 25.3.1 (x86_64-w64-mingw32) of 2017-09-17
* Installed emacs packages:
```
  company            20170926.1515
  company-quickhelp  20170429.1052
  dash               20170924.2240
  epl                20150517.433
  flycheck           20170911.127
  fsharp-mode        20170918.842
  pkg-info           20150517.443
  popup              20160709.729
  pos-tip            20150318.813
  powerline          20170708.1442
  s                  20170922.900
  spaceline          20170630.2327
```
* F# 4.1 (C:\Program Files (x86)\Microsoft SDKs\F#\4.1\Framework\v4.0)

**Comment by mzabolotko** [comment]
fsharp-mode works well on another machine with following configuration.

Windows 10 
GNU Emacs 25.2.1 (x86_64-w64-mingw32) of 2017-04-24
Installed packages:
```
  company            20170828.414  installed             Modular text completion framework
  fsharp-mode        20170918.842  installed             F# mode for Emacs
  magit              20170927.107  installed             A Git porcelain inside Emacs
  omnisharp          20170909.319  installed             Omnicompletion (intellisense) and more for C#
  spaceline          20170630.2327 installed             Modeline configuration library for powerline
  async              20170916.2256 dependency            Asynchronous processing in Emacs
  auto-complete      20170124.1845 dependency            Auto Completion for GNU Emacs
  company-quickhelp  20170429.1052 dependency            Popup documentation for completion candidates
  csharp-mode        20170502.158  dependency            C# mode derived mode
  dash               20170810.137  dependency            A modern list library for Emacs
  epl                20150517.433  dependency            Emacs Package Library
  f                  20170404.1039 dependency            Modern API for working with files and directories
  flycheck           20170911.127  dependency            On-the-fly syntax checking
  git-commit         20170914.258  dependency            Edit Git commit messages
  magit-popup        20170918.1116 dependency            Define prefix-infix-suffix command combos
  pkg-info           20150517.443  dependency            Information about packages
  popup              20160709.729  dependency            Visual Popup User Interface
  pos-tip            20150318.813  dependency            Show tooltip at point
  powerline          20170708.1442 dependency            Rewrite of Powerline
  s                  20170906.1304 dependency            The long lost Emacs string manipulation library.
  shut-up            20150423.522  dependency            Shut up would you!
  with-editor        20170927.1838 dependency            Use the Emacsclient as $EDITOR
```
I hope it will help.

**Comment by rneatherway** [comment]
Are you editing the same project? Different checkout location? I'm trying to work out what is different between the two.

**Comment by mzabolotko** [comment]
Yes, I am editing the same project at the same location (but different machines).  I have created the default F# library solution from Visual Studio and opened Library1.fs file.
There are some differences of emacs versions and some emacs packages: dash, s and others.

**Comment by rneatherway** [comment]
I think the problem is in fsharp-mode--msbuild-find. Could you try checking the value of the variable fsharp-build-command, and then also invoking (fsharp-mode--msbuild-find "msbuild")? Where is your msbuild.exe?

**Comment by mzabolotko** [comment]
fsharp-build-command value is nil
evaluation expression (fsharp-mode--msbuild-find "msbuild") returns nil
I have msbuild 15.0 only.

**Comment by rneatherway** [comment]
Makes sense, but can you tell me exactly where your msbuild.exe is? Perhaps inserting `"15.0"` will fix it here: https://github.com/fsharp/emacs-fsharp-mode/blob/master/fsharp-mode-util.el#L49

**Comment by rneatherway** [comment]
From looking at this issue (https://github.com/hoffi/gulp-msbuild/pull/47/files) it seems that it can be in a few different locations. Logic seems to be roughly:

root:

    'C:', is64Bit ? 'Program Files (x86)' : 'Program Files', 'Microsoft Visual Studio', '2017'

Plus one of:

    {'Enterprise', 'Professional', 'Community', 'BuildTools'}

Plus:

    'MSBuild', version (15.0), 'Bin', x64_dir, 'MSBuild.exe'

**Comment by mzabolotko** [comment]
I have installed the visual studio 2017 community edition. I found the msbuild at 
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin

**Comment by juergenhoetzel** [comment]
I also had this issue. I thought [using the registry](https://gist.github.com/jpluimers/9b9953050aab8e3e511f) is a good solution. But sadly this is a dead end and we can't expect [vswhere](https://github.com/Microsoft/vswhere/) is installed.

So I used the logic described by @rneatherway in my pull request.
