### ISSUE TITLE
Doesn't recognise absolute path of .fsproj file

### ISSUE THREAD

**Issue by tereshkin** [fsharp/emacs-fsharp-mode#155]
### Description

When I call `fsharp-ac/load-project` first it already suggest me to provide absolute path as I see following in the command input line: `Path to project (default try_fsharp.fsproj): ~/Programs/sandbox/try_fsharp/`. When I complete it as following `Path to project (default try_fsharp.fsproj): ~/Programs/sandbox/try_fsharp/try_fsharp.fsproj` and execute I get the following error: 

`ApplicationName=’dotnet’, CommandLine=’msbuild /Users/tereshkin/Programs/sandbox/try_fsharp/try_fsharp.fsproj /p:SkipCompilerExecution=true /p:ProvideCommandLineArgs=true /p:CopyBuildOutputToOutputDirectory=false /p:UseCommonOutputDirectory=true /t:_Inspect_FscArgs /p:_Inspect_FscArgs_OutFile=/var/folders/3g/3p8lwnjs4tl5nqbd51p6t6_00000gn/T/tmp16b0886d.tmp.FscArgs.txt /p:DesignTimeBuild=true /t:_Inspect_GetResolvedProjectReferences /p:_Inspect_GetResolvedProjectReferences_OutFile=/var/folders/3g/3p8lwnjs4tl5nqbd51p6t6_00000gn/T/tmp650ab246.tmp.GetResolvedProjectReferences.txt /t:_Inspect_GetProperties /p:_Inspect_GetProperties_OutFile=/var/folders/3g/3p8lwnjs4tl5nqbd51p6t6_00000gn/T/tmp650ab246.tmp.GetProperties.txt /nologo /verbosity:quiet’, CurrentDirectory=’/Users/tereshkin/Programs/sandbox/try_fsharp’, Native error= Cannot find the specified file`

However if I complete it as just `Path to project (default try_fsharp.fsproj): 
try_fsharp.fsproj` it seems to be Ok. But after I start using some features as "go to definition" parser complains that file isn't part of the project:

`Error: /Users/tereshkin/Programs/sandbox/try_fsharp/Program.fs is not part of the loaded projects.`

Project file:
[try_fsharp.fsproj.zip](https://github.com/fsharp/emacs-fsharp-mode/files/1523827/try_fsharp.fsproj.zip)

### Repro steps

1. Create F# .NET core project
2. Open emacs where fshrp-mode is installed
3. Try to load the project manually
4. Try to get auto completion

### Expected behavior

I shouldn't get an errors.
I should be able to use both absolute and relative paths.

### Actual behavior

Errors (see above).

### Known workarounds

Not known. Seems to be as some problem with my paths.

### Related information 

* OS X 10.13.1
* Emacs 25.1.1
* .NET Core 2.0.3, Mono 5.4.1.6

**Comment by tereshkin** [comment]
If I freshly open Emacs and open Program.fs I get:

`ApplicationName=’dotnet’, CommandLine=’msbuild /Users/tereshkin/Programs/sandbox/try_fsharp/try_fsharp.fsproj /p:SkipCompilerExecution=true /p:ProvideCommandLineArgs=true /p:CopyBuildOutputToOutputDirectory=false /p:UseCommonOutputDirectory=true /t:_Inspect_FscArgs /p:_Inspect_FscArgs_OutFile=/var/folders/3g/3p8lwnjs4tl5nqbd51p6t6_00000gn/T/tmp523913ab.tmp.FscArgs.txt /p:DesignTimeBuild=true /t:_Inspect_GetResolvedProjectReferences /p:_Inspect_GetResolvedProjectReferences_OutFile=/var/folders/3g/3p8lwnjs4tl5nqbd51p6t6_00000gn/T/tmp5db46859.tmp.GetResolvedProjectReferences.txt /t:_Inspect_GetProperties /p:_Inspect_GetProperties_OutFile=/var/folders/3g/3p8lwnjs4tl5nqbd51p6t6_00000gn/T/tmp6eed675e.tmp.GetProperties.txt /nologo /verbosity:quiet’, CurrentDirectory=’/Users/tereshkin/Programs/sandbox/try_fsharp’, Native error= Cannot find the specified file
Error: /Users/tereshkin/Programs/sandbox/try_fsharp/Program.fs is not part of the loaded projects.`

**Comment by tereshkin** [comment]
Okay...

Really my problem could be that I had both .bash_profile and .bashrc in my system. Or probably reinstallation of `mono` using `brew` helped (spoiler: it's tricky with High Sierra).

I'll let somebody else to close the issue.

**Comment by rneatherway** [comment]
Glad it's working :-)
