### ISSUE TITLE
fsharp-mode sets comment-indent-function globally

### ISSUE THREAD

**Issue by retroj** [fsharp/emacs-fsharp-mode#156]
### Description

fsharp-mode sets comment-indent-function globally to fsharp-comment-indent-function, and this interferes with indentation in other major modes.

### Repro steps

1. Use fsharp-mode.

2. Go into a non-fsharp buffer and `C-h v comment-indent-function` to see the global value of comment-indent-function.

### Expected behavior

fsharp-mode should only set the buffer-local value of comment-indent-function within fsharp buffers, not the global value.

### Related information 

* tested with fsharp-mode version 1.9.1

**Comment by rneatherway** [comment]
Thanks for the report.
