### ISSUE TITLE
Project File not Reloading

### ISSUE THREAD

**Issue by angrydexterous** [fsharp/emacs-fsharp-mode#158]
### Description

Please provide a succinct description of your issue.

### Repro steps

Please provide the steps required to reproduce the problem

1. open System.Data

2. Get error about namespace not being defined

3. Add System.Data to fsproj file

4. Still get error about namespace not being defined

5. C-c C-p to reload proj file

### Expected behavior

Project file should reload, error on open should disappear 

### Actual behavior

Error persists until emacs restart

### Known workarounds

Restart emacs

### Related information 

* Ubuntu 16.04
* Emacs version 25.2.1
* Mono 5.8.0.108

**Comment by juergenhoetzel** [comment]
Another workaround: Editing the buffer (so the buffer gets *flychecked* again)?

**Comment by juergenhoetzel** [comment]
Should be fixed upstream: [Flycheck: Allow running syntax check after buffer switch](https://github.com/flycheck/flycheck/pull/1308)

**Comment by juergenhoetzel** [comment]
Upstream merged.
