### ISSUE TITLE
Auto-completion in list literals strips delimiters away.

### ISSUE THREAD

**Issue by j-em** [fsharp/emacs-fsharp-mode#161]
### Description

Triggering auto-completion on an identifier that is preceded by `[` removes the `[` itself on candidate insertion.

### Repro steps
1. Type in the following code.

```fsharp
type Animal = Dog | Cat

let animals = [Do//<- cursor is here
```

2. Trigger `company-complete` while cursor is right after `[Do`

3. Select the `Dog` candidate in company UI.

### Expected behavior

`Do` gets auto-completed to `Dog` while the leading `[` stays intact.

#### Code before auto-completion
```fsharp
type Animal = Dog | Cat
let animals = [Do
```

#### Code after auto-completion
```fsharp
type Animal = Dog | Cat 
let animals = [Dog
```

### Actual behavior

`Do` gets auto-completed to `Dog` while the leading `[` is stripped away.

#### Code before auto-completion
```fsharp
type Animal = Dog | Cat
let animals = [Do
```

#### Code after auto-completion
```fsharp
type Animal = Dog | Cat
let animals = Dog
```

### Known workarounds
Inserting a space between the opening bracket and the first element of the list makes the auto-completion work properly again.

### Related information 

* Ubuntu 16.04 LTS
* Emacs 24.5.1 & Emacs 27.0.50 (Tested on both)
* Mono 5.10 & .NET Core 2.0.3

**Comment by juergenhoetzel** [comment]
Confirmed, cause:  `(fsharp-ac-get-prefix)` return mistakenly `[Do` in this case.
