### ISSUE TITLE
"Error while checking syntax automatically" when visiting a new file

### ISSUE THREAD

**Issue by ysalmon** [fsharp/emacs-fsharp-mode#167]
### Description

I get Error while checking syntax automatically when visiting a new file.

### Repro steps

Please provide the steps required to reproduce the problem

1. Visit a new file ```/tmp/a.fsx```.

### Expected behavior

fsharp-mode loads and is ready to be used.

### Actual behavior

fsharp-mode loads and gives the following error.

```
Debugger entered--Lisp error: (error "Buffer a.fsx has no process")
  signal(error ("Buffer a.fsx has no process"))
  #[257 "\300 \210\301@A\"\207" [flycheck-report-failed-syntax-check signal] 4 "\n\n(fn ERR)"]((error "Buffer a.fsx has no process"))
  funcall(#[257 "\300 \210\301@A\"\207" [flycheck-report-failed-syntax-check signal] 4 "\n\n(fn ERR)"] (error "Buffer a.fsx has no process"))
  flycheck-buffer()
  #[0 "\300 \207" [flycheck-buffer] 1 "\n\n(fn)"]()
  funcall(#[0 "\300 \207" [flycheck-buffer] 1 "\n\n(fn)"])
  flycheck-buffer-automatically()
  flycheck-perform-deferred-syntax-check()
  set-window-buffer(nil #<buffer a.fsx>)
  switch-to-buffer(#<buffer a.fsx>)
  find-file("/tmp/a.fsx" t)
  funcall-interactively(find-file "/tmp/a.fsx" t)
```
### Known workarounds

none

### Related information 

* Operating system XUbuntu 16.04
* Branch
* Emacs version 25.3.2
* .NET Runtime, CoreCLR or Mono Version Mono JIT compiler version 5.12.0.226 
* Performance information, links to performance testing scripts
* Flycheck version 31
* fsharp-mode version 20171021.431

**Comment by juergenhoetzel** [comment]
I can confirm this issue.

I added a flycheck predicate function in [Pull Request: Add predicate function (WIP)](https://github.com/fsharp/emacs-fsharp-mode/pull/168).

Unfortunately this broke integration tests: I need to check it out.
