### ISSUE TITLE
Phrase detection error

### ISSUE THREAD

**Issue by ysalmon** [fsharp/emacs-fsharp-mode#171]
### Description

fsharp-mode does not accurately finds the whole phrase with an if/then/else construct.

### Repro steps
Type the follwong, set th text cursoron the closing parenthesis. I used "mark phrase" for the screenshot, but evaluating the phrase gives en F# error ``error FS0010: Unexpected keyword 'else' in interaction``
![capture d ecran_2018-05-17_22-04-18](https://user-images.githubusercontent.com/536850/40201256-da21192e-5a1e-11e8-83db-c76ed01ad30b.png)

### Expected behavior

I would expect the whole let rec to be considered as the phrase.

### Actual behavior

Please provide a description of the actual behaviour you observe. 

### Known workarounds

Selecting phrase manually and using evaluate region.

### Related information 

* Operating system Linux
* Branch XUbuntu 16.04
* Emacs version 25
* .NET Runtime, CoreCLR or Mono Version
* Performance information, links to performance testing scripts

**Comment by juergenhoetzel** [comment]
@ysalmon  Should be fixed in master branch: [Fix phrase detection error ](https://github.com/fsharp/emacs-fsharp-mode/pull/173)

Can you confirm?

**Comment by ysalmon** [comment]
Yes it is. Thanks !

**Comment by ysalmon** [comment]
Well, we are note quite there yet :
![capture d ecran_2018-05-21_19-17-52](https://user-images.githubusercontent.com/536850/40320361-bcf7a33a-5d2b-11e8-859e-afb829cbf222.png)

**Comment by juergenhoetzel** [comment]
Confirmed! 
This one is harder: Currently `fsharp-mode` doesn't handle mutual recursive type definitions correctly.

**Comment by ysalmon** [comment]
Would not a "from ``;;`` to ``;;``" approach work ? I do not remember how they do it in tuareg, but they surely cannot rely on indentation as it is not meaningful in OCaml.

**Comment by ysalmon** [comment]
When using OCaml in interactive mode (and fsharpi as well I think), you have to append ``;;`` to phrases, so that ocaml knows that it is complete.

It is also customary to append ``;;`` to phrases when typing code in Emacs/tuareg to evaluate them in interactive mode (in earlier versions of Caml, namely Caml Light, ``;;`` was even part of the language). This does not cause any problem because in compilation mode (ocamlc), these ``;;`` are simply ignored.

I do not know if this habit also exists in F#, but it makes it convenient to detect phrases : they are, in practice, the text that lies between two ``;;``s.  So one does not have to reimplement the F# syntax analyser in EmacsLisp. The only difficulty is agreeing on what "phrase under the text cursor" means : https://github.com/ocaml/tuareg/issues/158

**Comment by juergenhoetzel** [comment]
> I do not know if this habit also exists in F#, but it makes it convenient to detect phrases : they are, in practice, the text that lies between two ;;s. So one does not have to reimplement the whole F# syntax analyser in EmacsLisp. The only difficulty is agreeing on what "phrase under the text cursor" means : ocaml/tuareg#158

Thanks for the explanation. But this would require Users to use _";;_ " to explicitly seperate phrases in the Source files?

I consider another workaround: checking if first token in phrase is _and_ and recursively call `(fsharp-beginning-of-block)` in this case.

**Comment by ysalmon** [comment]
Yes, but it would also let them control what part of the code should be (re)executed by C-c C-e (maybe several F# statements). tuareg also has an "execute the whole file" command with shortcut C-c C-b.

**Comment by juergenhoetzel** [comment]
> This one is harder: Currently fsharp-mode doesn't handle mutual recursive type definitions correctly.

This should be fixed in master: [Handle mutually recursive definitions in phrase detection](https://github.com/fsharp/emacs-fsharp-mode/pull/174)

> Yes, but it would also let them control what part of the code should be (re)executed by C-c C-e (maybe several F# statements). tuareg also has an "execute the whole file" command with shortcut C-c C-b.

In `fsharp-mode` we already have:

<kbd>C-c C-f</kbd>  runs the command `fsharp-load-buffer-file`
<kbd>C-c C-r</kbd>  runs the command `fsharp-eval-region`

I definitely see a use-case for your proposed solution. But to be honest, the `fsharp-mode` indentation/parsing code is not in good shape and could use [](https://github.com/fsharp/emacs-fsharp-mode/issues/68)  some help from additional contributors (before adding more features).

**Comment by juergenhoetzel** [comment]
fixed in master: [Handle mutually recursive definitions in phrase detection](https://github.com/fsharp/emacs-fsharp-mode/pull/174)

**Comment by ysalmon** [comment]
Hello,
I tested this today
```
type 'a arbre =
    | Vide
    | Noeud of 'a cellule
and 'a cellule =
    {e: 'a; g: 'a arbre; d: 'a arbre};;
```
and C-c C-e on the last line gives ```error FS0010: Unexpected keyword 'and' in interaction```.

Note that while typing the code, I got several ```Possible incorrect indentation: this token is offside of context started at position (1:1). Try indenting this token further or using standard formatting conventions.```
