### ISSUE TITLE
.fs files not parsed

### ISSUE THREAD

**Issue by johesoman** [fsharp/emacs-fsharp-mode#182]
### Description

Fsharp mode works fine the first time I work with a project (right after creating it), I can add new files and everything. Next time I load up Emacs, fsharp mode can't parse the .fs files.

### Repro steps

1. Create new project with dotnet CLI.

2. Open newly created file Program.fs in Emacs.

3. Close Emacs.

4. Open Program.fs in Emacs again.

### Expected behavior

Working auto-completion.

### Actual behavior

Auto-completion does not work.

### fsharp-debug output

14:19:18.567324: project "/home/mrj/Desktop/test/test.fsproj" verbose
14:19:18.574015: {"Kind":"project","Data":{"Project":"/home/mrj/Desktop/test/test.fsproj","Files":["/home/mrj/Desktop/test/obj/Debug/netcoreapp2.1/test.AssemblyInfo.fs","/home/mrj/Desktop/test/Stuff.fs","/home/mrj/Desktop/test/Program.fs"],"Output":"/home/mrj/Desktop/test/obj/Debug/netcoreapp2.1/test.dll","References":[],"Logs":{},"OutputType":"exe","Info":{"SdkType":"dotnet/sdk","Data":{"IsTestProject":false,"Configuration":"Debug","IsPackable":true,"TargetFramework":"netcoreapp2.1","TargetFrameworkIdentifier":".NETCoreApp","TargetFrameworkVersion":"v2.1","RestoreSuccess":true,"TargetFrameworks":[],"RunCmd":{"Command":"dotnet","Arguments":"exec \"/home/mrj/Desktop/test/bin/Debug/netcoreapp2.1/test.dll\""},"IsPublishable":true}},"AdditionalInfo":{}}}
14:19:18.574283: Received ’project’ message of length 2
14:27:11.909466: typesig "/home/mrj/Desktop/test/Program.fs" "let f =" 5 1 400 
14:27:11.910019: symboluse "/home/mrj/Desktop/test/Program.fs" "let f =" 5 1 400 
14:27:11.927784: {"Kind":"error","Data":{"Code":1,"Message":"File '/home/mrj/Desktop/test/Program.fs' not parsed","AdditionalData":{}}}
14:27:11.927867: Received ’error’ message of length 2
14:27:11.948595: {"Kind":"error","Data":{"Code":1,"Message":"File '/home/mrj/Desktop/test/Program.fs' not parsed","AdditionalData":{}}}
14:27:11.948676: Received ’error’ message of length 2
14:27:42.000120: project "/home/mrj/Desktop/test/test.fsproj" verbose
14:27:42.004767: {"Kind":"project","Data":{"Project":"/home/mrj/Desktop/test/test.fsproj","Files":["/home/mrj/Desktop/test/obj/Debug/netcoreapp2.1/test.AssemblyInfo.fs","/home/mrj/Desktop/test/Stuff.fs","/home/mrj/Desktop/test/Program.fs"],"Output":"/home/mrj/Desktop/test/obj/Debug/netcoreapp2.1/test.dll","References":[],"Logs":{},"OutputType":"exe","Info":{"SdkType":"dotnet/sdk","Data":{"IsTestProject":false,"Configuration":"Debug","IsPackable":true,"TargetFramework":"netcoreapp2.1","TargetFrameworkIdentifier":".NETCoreApp","TargetFrameworkVersion":"v2.1","RestoreSuccess":true,"TargetFrameworks":[],"RunCmd":{"Command":"dotnet","Arguments":"exec \"/home/mrj/Desktop/test/bin/Debug/netcoreapp2.1/test.dll\""},"IsPublishable":true}},"AdditionalInfo":{}}}
14:27:42.005172: Received ’project’ message of length 2

### Related information 

* Linux, Manjaro 17.1.10
* Emacs 26.1
* .NET Core 2.1.300

**Comment by juergenhoetzel** [comment]
Fixed in 1.9.3
