### ISSUE TITLE
BUG: fsharp-mode globally turns on company-quickhelp-mode

### ISSUE THREAD

**Issue by ilohmar** [fsharp/emacs-fsharp-mode#198]
### Description

See title.

### Repro steps

Turn on `fsharp-mode`.

### Expected behavior

Leaves alone all settings outside of fsharp-mode buffers.

### Actual behavior

Turns on `company-quickhelp-mode`, if bound.

**Comment by juergenhoetzel** [comment]
Thanks! Fixed in master (#199)
