### ISSUE TITLE
indentation issues

### ISSUE THREAD

**Issue by ryrun** [fsharp/emacs-fsharp-mode#23]
There some "auto" indentation issues:
```fsharp
//I try to get this
let add1 x =
  x + 1

let add2 y =
  y + 1
```

```fsharp
//And the auto indentation force me to write this
let add1 x =
  x + 1

  let add2 y =
    y + 1
```

Other example, here you cant use tab, you must use space:
```fsharp
//i want to write this
let prn x = System
              .Console
              .WriteLine (x.ToString())
```
```fsharp
//auto indentation force me to write this
let prn x = System
.Console
.WriteLine (x.ToString)
```

**Comment by rneatherway** [comment]
Yes, there are many such bugs (see #11 for another). I inherited the auto-indentation years ago when I took over maintaining the mode and I never found time to redo it.

One thing I would say is that it can't please everyone's styles, so we need to settle on something reasonably opinionated, but not too much so.

For your first example, the expectation would I think to use backspace before the second `let`. For the second example, when does it reset to the left margin? On `.`?

**Comment by ryrun** [comment]
Its ok, when the auto-indentation 'sometimes' doesn't do the right thing, but its bad, when the auto indentation prevent manual indentation with the tab key or automatically do wrong indentation. 

```fsharp
let add1 x =
  x + 1

let add2 y =  <-- move the cursor to the end of this line and press enter
  y + 1
```

```fsharp
let prn x = System <-- move the cursor to the end of this line, press enter and try to use the tab key
```

I'm not sure, how the indentation is working in visual studio with fsharp code, but this kind of auto-indentation could be frustrating most of the time. Maybe it should only apply auto-indentation on new empty lines and nothing more and it should allow the user to use the tab key all the time.

**Comment by ryrun** [comment]
I've checked visual studio, it doesn't have auto indentation. It just indent the new line, with the same indentation level like the current one. I think this would be the best.
I tried to disable the auto indentation in fsharp-mode:
```elisp
(add-hook 'fsharp-mode-hook
 (lambda ()
   (setq fsharp-smart-indentation nil)
   (setq fsharp-tab-always-indent nil)))
```
But it doesn't work.

**Comment by rneatherway** [comment]
> I'm not sure, how the indentation is working in visual studio with fsharp code, but this kind of auto-indentation could be frustrating most of the time. Maybe it should only apply auto-indentation on new empty lines and nothing more and it should allow the user to use the tab key all the time.

Yes, we could perhaps do a bit better than that (indent on function definition/trailing `=` and similar), but what you suggest would probably be better than the current situation.

I think what you want is to rebind `C-m`, which is currently bound to `fsharp-newline-and-indent`, to just a newline or something like that. If you are feeling more adventurous then a PR to remove most of `fsharp-mode-indent.el` and replace it with something much simpler would be great.

**Comment by ryrun** [comment]
My elisp skills are too basic for this :)
Maybe "haskell-mode" or "ocalm-mode" could be a good base for a new implementation.
The current indentation makes the fsharp-mode not very usable, at least for me. Do you actively working on this?

**Comment by rneatherway** [comment]
I am actively working on this repo, yes, but not currently on this indentation issue. I support multiple other projects as well and I don't have a lot of time at the moment. I do think this is important and I will get to it when I can.

Btw, I think this originally came from "ocaml-mode", as F# used to be almost identical.

**Comment by ryrun** [comment]
I found `stupid-indent-mode` which have a similar indentation like visual studio. Seems it works great, need some bugfixing, but it works.

**Comment by cando** [comment]
Same problem here. It seems that #34 doesn't fix it.

**Comment by rneatherway** [comment]
Hi @cando, could you give some example text I can try typing in to reproduce the bad behaviour?

**Comment by cando** [comment]
If I type the original example in this issue i get the problem. 
When I type enter after "let add2 y = " the whole let sentence is intended wrongly as @ryrun reported.
Thanks!

**Comment by rneatherway** [comment]
I can't reproduce here, it just indents by 4 and does not change the indentation of the `let` line.

**Comment by cando** [comment]
I'm using GNU Emacs 24.5.1 and this is my .emacs file. Can you see anything wrong?

```
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(inhibit-startup-screen t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )

(setq url-proxy-services '(("http" . "localhost:3128")))

(require 'package) ;; You might already have this line
(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/"))
(when (< emacs-major-version 24)
  ;; For important compatibility libraries like cl-lib
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
(package-initialize) ;; You might already have this line

(global-set-key (kbd "°") (kbd "`"))
(global-set-key (kbd "§") (kbd "~"))

(setq backup-directory-alist
          `((".*" . ,temporary-file-directory)))
(setq auto-save-file-name-transforms
          `((".*" ,temporary-file-directory t)))

(require 'icicles)
(icy-mode 1)
(setq icicle-buffer-include-recent-files-nflag 1000)

(require 'web-mode)
(add-to-list 'auto-mode-alist '("\\.phtml\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.tpl\\.php\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.[agj]sp\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.as[cp]x\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.erb\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.mustache\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.djhtml\\'" . web-mode))
(add-to-list 'auto-mode-alist '("\\.html?\\'" . web-mode))

;; use Shift+arrow_keys to move cursor around split panes
(windmove-default-keybindings)

;; when cursor is on edge, move to the other side, as in a torus space
(setq windmove-wrap-around t )

;; dabbrev
(global-set-key (kbd "C-<tab>") 'dabbrev-expand)
(define-key minibuffer-local-map (kbd "C-<tab>") 'dabbrev-expand)

(require 'vbasense)

;; Keybinding
(setq vbasense-popup-help-key "C-:")
(setq vbasense-jump-to-definition-key "C->")

;; Do setting a recommemded configuration
(vbasense-config-default)

(require 'recentf)
(recentf-mode 1)
(setq recentf-max-menu-items 1000)

;; Org-mode settings
(add-to-list 'auto-mode-alist '("\\.org$" . org-mode))
(global-set-key "\C-cl" 'org-store-link)
(global-set-key "\C-ca" 'org-agenda)

;;; Install fsharp-mode
(unless (package-installed-p 'fsharp-mode)
  (package-install 'fsharp-mode))

(require 'fsharp-mode)
```

**Comment by rneatherway** [comment]
I'm also using Emacs 24.5.1. I tried to start up with your file by putting it in an empty dir and running `HOME=`pwd` emacs` but it fails due to missing packages. Even after commenting them out I get:

> error: Package `fsharp-mode-' is unavailable

**Comment by joranvar** [comment]
I have the same problem under 24.5.2, when I start with `emacs -Q`, then evaluate `(package-initialize)` and `(require 'fsharp-mode)`. While stepping through `fsharp-newline-and-indent`, I find that `newline-and-indent` calls `newline`, and the culprit seems to be `electric-indent-post-self-insert-function`, which is somehow hooked to `post-self-insert-hook`.

**Comment by cando** [comment]
@joranvar fix works for me. Thanks!

**Comment by rneatherway** [comment]
Haha you're absolutely right. When I started with `-Q` and hunted for how I load `fsharp-mode` locally I found this cheeky line:

    (add-hook 'fsharp-mode-hook (lambda () (electric-indent-local-mode -1)))

Thanks for the PR, I'll merge that and release a new version to MELPA.

**Comment by joranvar** [comment]
Haha, yes, those quick workarounds do tend to sneak up on us developres :P Thanks for merging!

**Comment by flypixel** [comment]
For everyone who continues to have an issue with auto indentation (because I have) and doesn't  know how to switch it off in fsharp-mode, there is a just hack solution (but it works better than auto-indentation): 
```lisp
(setq indent-region-function '(lambda (start end &optional indent-offset)))
``` 
I hope these problems will be resolved.
P.S. I use 20160205.700 version of fsharp-mode from melpa or 1.7.3  from stable-melpa, and they still have these issues.

**Comment by rneatherway** [comment]
@flypixel sorry to hear you're still having issues. Please could you open a new issue with steps for me to reproduce?

**Comment by kuznero** [comment]
This question is not directly related to this thread, only somewhat. How do I change tab width from 4 to 2 in fsharp-mode in Emacs?

**Comment by kuznero** [comment]
Done, [PR](https://github.com/fsharp/emacs-fsharp-mode/pull/89).
