### ISSUE TITLE
Autocomplete is not working after update.

### ISSUE THREAD

**Issue by KnightOfTribulus** [fsharp/emacs-fsharp-mode#238]
### Description
After the update autocomplete is completely broken.
Fsautocomplete is installed, fsharp-mode and eglot are running, but there is no autocomplete popup menu.

### Repro steps
Here is the part of my .emacs responsible for loading fsharp-mode:

(require 'fsharp-mode)
(require 'eglot-fsharp)
(add-hook 'fsharp-mode-hook #'eglot-ensure)
(setq inferior-fsharp-program "dotnet fsi")
(add-to-list 'auto-mode-alist '("\.fs[iylx]?$" . fsharp-mode))

### Expected behavior

Autocomplete with popup menu in fsharp buffers after load.

### Actual behavior

Fsharp mode is working, eglot loads successfully, but autocomplete is not working.
Type signatures and tool tips are displayed in the mode line.

### Known workarounds

I didn't find any workarounds.

### Related information 

* Operating system
OS: Ubuntu 19.10 x86_64
Kernel: 5.3.0-26-generic

* Emacs version
GNU Emacs 26.3

* .NET Runtime, CoreCLR or Mono Version
dotnet 3.0.102;
Mono JIT compiler version 6.8.0.96 (tarball Wed Jan 15 10:08:18 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)

**Comment by juergenhoetzel** [comment]
> After the update autocomplete is completely broken.
> Fsautocomplete is installed, fsharp-mode and eglot are running, but there is no autocomplete popup menu.

I can't reproduce using the latest `fsautocomplete` builds:

Did you `dotnet restore` the project you are working on?

**Comment by KnightOfTribulus** [comment]
Yes, I did. It didn't help.

**Comment by juergenhoetzel** [comment]
> Yes, I did. It didn't help.

Would you mind to restore/test the project in the `test/test1` subdirectory? This project is also used in the travis test.

Please also post the
```
*EGLOT (Test1/fsharp-mode) events*
*EGLOT (Test1/fsharp-mode) stderr*
```
buffers.

**Comment by KnightOfTribulus** [comment]
Of course. I successfully restored the project in the directory you mentioned. When I open one of the files in this project in emacs I have no autocomplete, but fsautocomplete.dll is running as a background service. 

*EGLOT (Test1/fsharp-mode) stderr* is empty.

Here is the contents of *EGLOT (Test1/fsharp-mode) events*:
https://gist.github.com/KnightOfTribulus/1d95195539002aedffcf9604937f259e
The file is quite large, so I decided to upload it separately.

**Comment by KnightOfTribulus** [comment]
I'm sorry, it seems to be my bad. Completion works when I manually call the function _complete-symbol_, and I get the list of completions in a separate buffer *\*Completions\**. I expected it to work with a popup menu out of the box as it was before the update and I still have no idea how to make it work.

**Comment by KnightOfTribulus** [comment]
Well, it works as intended after adding the following lines to the emacs config:
```
(add-hook 'fsharp-mode-hook 'dotnet-mode)
(add-hook 'fsharp-mode-hook 'company-mode)
(setq inferior-fsharp-program "fsharpi --readline-")
```
It was so simple... Sorry, I'm closing the issue.
