### ISSUE TITLE
installation error on OSX

### ISSUE THREAD

**Issue by m00nlight** [fsharp/emacs-fsharp-mode#24]
I install the fsharp-mode from melpa with version `20150902.732`, but when I open an f-sharp file, it report the following error:

```
Debugger entered--Lisp error: (void-function -any)
  (-any (quote fsharp-mode--executable-find) (quote ("fsharpc" "fsc")))
  (defvar fsharp-compile-command (-any (quote fsharp-mode--executable-find) (quote ("fsharpc" "fsc"))) ("/Users/m00nlight/.emacs.d/elpa/fsharp-mode-20150902.732/fsharp-mode.elc" . 595))
  fsharp-mode()
  set-auto-mode-0(fsharp-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(t t)
  find-file-noselect-1(#<buffer test.fs> "~/Documents/tmp/test.fs" nil nil "~/Documents/tmp/test.fs" nil)
  find-file-noselect("~/Documents/tmp/test.fs" nil nil t)
  find-file("~/Documents/tmp/test.fs" t)
  call-interactively(find-file nil nil)
  command-execute(find-file)
```

My configuration for f-sharp mode is as follow:

```elisp
(add-to-list 'load-path "~/.emacs.d/elpa/fsharp-mode-20150902.732/")

(setq inferior-fsharp-program "/usr/local/bin/fsharpi --readline-")
(setq fsharp-compiler "/usr/local/bin/fsharpc")

(autoload 'fsharp-mode "fsharp-mode" 
  "Major mode for editing F# code." t)
(add-to-list
 'auto-mode-alist '("\\.fs[iylx]?$" . fsharp-mode))
```

It seems can not find the function `-any`.  Is there anything wrong with my configuration?
I am under OSX with GNU emacs 24.5.1.

**Comment by rneatherway** [comment]
`-any` is provided by the dependency library `dash.el`, which should also have been installed by MELPA. Generally you should allow the packages to be loaded by Emacs' package manager, following the instructions at http://melpa.org/#/getting-started. (You shouldn't add `fsharp-mode-20150902.732` to the `load-path` yourself)

**Comment by m00nlight** [comment]
In fact, I first tried the instruction on the read-me. But it show the following error when I started Emacs

```
Warning (initialization): An error occurred while loading `/Users/m00nlight/.emacs':

Symbol's function definition is void: -any

To ensure normal operation, you should investigate and remove the
cause of the error in your initialization file.  Start Emacs with
the `--debug-init' option to view a complete error backtrace.
```

Configuration:

```elisp
;;; Initialize MELPA
(require 'package)
(add-to-list 'package-archives
             '("melpa" . "https://melpa.org/packages/"))
(unless package-archive-contents (package-refresh-contents))
(package-initialize)

;;; Install fsharp-mode
(unless (package-installed-p 'fsharp-mode)
  (package-install 'fsharp-mode))

(require 'fsharp-mode)
```

**Comment by m00nlight** [comment]
Find out the reason. It is because I already installed an old version of dash library, 2014XX version, which seems do not have the `-any` definition required for fsharp mode. When I update dash to the latest version. Everything is fine.  Maybe the document should update to indicate the problem?

**Comment by rneatherway** [comment]
Ah I see. This is unfortunate. It is because MELPA uses the dates for the versions and so breaks proper dependency specifications. You suggest updating the README to mention this?

**Comment by m00nlight** [comment]
Yes. Maybe add some section like trouble shooting, which can point out normal problems to avoid using the package?

**Comment by rneatherway** [comment]
OK, I have just updated the Troubleshooting section. Does that look OK?

**Comment by m00nlight** [comment]
Looks fine :+1: .  

Another problem. When I edit a test.fsx file and then select all the buffer, and run `C-c C-r` to evaluate the region. It shows the error:

```
/usr/local/bin/fsharpi: line 24: exec: mono: not found

Process inferior-fsharp exited abnormally with code 127
```

I already add the configuration like in the read-me.

```elisp
(setq inferior-fsharp-program "/usr/local/bin/fsharpi --readline-")
(setq fsharp-compiler "/usr/local/bin/fsharpc")
```

And how can I started an REPL in Emacs and evaluate expression on fly?

**Comment by rneatherway** [comment]
Please can you try running on the command line: `/usr/local/bin/fsharpi tmp.fsx` ?

**Comment by m00nlight** [comment]
Yes. I can run it from the command line.

```bash
➜  tmp  fsharpi test.fsx < test.in
[22; *; 79; ... ]
1717
➜  tmp  /usr/local/bin/fsharpi test.fsx < test.in
[22; *; 79; ... ]
1717
```

**Comment by rneatherway** [comment]
Hmm, it seems like your PATH in Emacs may not be the same as in bash. The error given by emacs is when executing the fsharpi script.

**Comment by m00nlight** [comment]
Yes. After examine the "PATH" env of the shell and in Emacs, I found that `/usr/local/bin/` was not in the "PATH" env in emacs. After add `/usr/local/bin` to "PATH" in emacs. Now I can start the interpreter. 

Thanks for your kindly help :)

**Comment by rneatherway** [comment]
Great!
