### ISSUE TITLE
 Failed to install fsharp-mode: Package ‘emacs-26.3’ is unavailable when use 26.1

### ISSUE THREAD

**Issue by madosuki** [fsharp/emacs-fsharp-mode#241]
### Description

Failed to install fsharp-mode: Package ‘emacs-26.3’ is unavailable on Emacs 26.1 with Debian buster.
Cause at both melpa and melpa-stable.

### Repro steps

1. Step A
M-x package-refresh-contents

2. Step B
M-x package-list-packages

3. Step C
Choose fsharp-mode and do install.

### Related information 

* Operating system 
Debian 4.19.118-2+deb10u1 (2020-06-07) x86_64 GNU/Linux

* Emacs version
26.1

**Comment by juergenhoetzel** [comment]
This is due to a transitive dependency of `eglot`: [eldoc](http://elpa.gnu.org/packages/eldoc-1.10.0.el) which requires Emacs 26.3
