### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by bradyt** [fsharp/emacs-fsharp-mode#244]
With,

```elisp
(setq package-archives
      '(("gnu" . "https://elpa.gnu.org/packages/")
	("melpa" . "https://melpa.org/packages/")))
```

I try `M-x package-install RET fsharp-mode RET` and I get, `Package ‘flymake-1.0.9’ is unavailable`, and fsharp-mode is not installed.

On a new Windows 10 session, and a new Emacs build from gnu.org, version 27.1, the flymake version is 1.0.8.

I'm guessing it's a combination of the commit "[Add eglot dependency](https://github.com/fsharp/emacs-fsharp-mode/commit/7d12f1658b3637151166219f635fe0281fcdcfdd)" at present repo and the commit "[* eglot.el (Package-Requires): Require Flymake 1.0.9 and eldoc 1.2.0 ](https://github.com/joaotavora/eglot/commit/433779dbd27e1a9678e4c6cd4189c65d1900665a)" at the eglot repo.

I realize the preference might be to wait until a newer version of Emacs is provided, or that situation improves otherwise. While fsharp might be a Microsoft thing, I'm not sure the majority of emacs-fsharp-mode users are actually on Windows. So maybe this issue can be closed. There is currently an Emacs 28 available for Windows as a pretest.

**Comment by juergenhoetzel** [comment]
> I realize the preference might be to wait until a newer version of Emacs is provided, or that situation improves otherwise. While fsharp might be a Microsoft thing, I'm not sure the majority of emacs-fsharp-mode users are actually on Windows. So maybe this issue can be closed. There is currently an Emacs 28 available for Windows as a pretest.

This should work out-of-the-box. The Same Emacs version is used in the [CI Job:](https://github.com/fsharp/emacs-fsharp-mode/pull/250/checks?check_run_id=1205254130)

```
  shows flymake errors
  shows flymake errors (17.56s)
```

I suspect this was a temporary Elpa Problem (flymake is not available on melpa)?

**Comment by 3Rafal** [comment]
I've had a similar problem. Added `(package-refresh-contents)` after setting package-archives and it works ok.

**Comment by bradyt** [comment]
If this issue already had a low chance of occurrence, I'm guessing it's even lower now, with newer Emacs, possibly improved infrastructure at Elpa, and newer fsharp-mode. I will close now.
