### ISSUE TITLE
FsAutoComplete installation is not working

### ISSUE THREAD

**Issue by eglyph** [fsharp/emacs-fsharp-mode#245]
### Description

Installation of FsAutoComplete from appveyor is not working, possibly because of changes in Appveyor builds. 

### Repro steps

1. Install `fsharp-mode` from melpa
2. Follow instructions for enabling `eglot`

### Expected behavior

FsAutoComplete installed correctly and `eglot-fsharp` working as expected. 

### Actual behavior

A message "Failed to unzip fsautocomplete.zip" is displayed and installation is aborted. The file itself is not a valid zip archive, it's a text file containing a JSON `{"message":"Artifact not found or access denied."}`

### Known workarounds

Manually cloning FsAutoComplete into `.emacs.d`, building it and copying `bin/release_netcore` to `netcore` fixes the problem. 

### Related information 

* Operating system is MacOS
* Branch is master
* GNU Emacs 27.1 (build 1, x86_64-apple-darwin19.6.0, NS appkit-1894.60 Version 10.15.6 (Build 19G73)) of 2020-08-12
* .NET Runtime version is 3.1

**Comment by juergenhoetzel** [comment]
Fixed by #246
