### ISSUE TITLE
Tab key can not indent to correct position

### ISSUE THREAD

**Issue by m00nlight** [fsharp/emacs-fsharp-mode#26]
For the following code

```f#
let f1 x y = 
```

When I place the cursor after the function definition line, and press `tab` key, it can not 
indent to the correct position like other programmer mode, just stay at the beginning of
the line. 

Is there a way to set `tab` key to indent to the correct position?

**Comment by rneatherway** [comment]
Please see #23 and #11. This needs rewriting from scratch, but I haven't had time yet.

**Comment by m00nlight** [comment]
How about follow the example of SML-mode, using SIME to implement the indentation? If this idea is OK, I can try to patch a pull request for indentation.

**Comment by rneatherway** [comment]
That would be great! Thanks for offering.

**Comment by m00nlight** [comment]
@rneatherway  Sorry for the late pull request #34 , since I have some other things to do recently and I am also newbie to F#, and not very familiar with SMIE.

 It is still a very basic indentation, something like the beginning of function body can not be handle, we still need to manually indent to the correct position at the beginning of function body, but luckily , the remaining code in the function body can be automatically indent to correct position. I will continue to improve the indentation code if you think it is useful.

**Comment by rneatherway** [comment]
Fixed by #34
