### ISSUE TITLE
No such file or directory, eglot

### ISSUE THREAD

**Issue by jcs090218** [fsharp/emacs-fsharp-mode#265]
I am getting the error this message while installing.

```
eglot-fsharp.el:30:1:Error: Cannot open load file: No such file or directory, eglot
```

I think we are still downloading the file `eglot-fsharp.el` even we have splitted up the package?

**Comment by juergenhoetzel** [comment]
> I am getting the error this message while installing.
> 
> ```
> eglot-fsharp.el:30:1:Error: Cannot open load file: No such file or directory, eglot
> ```
> 
> I think we are still downloading the file `eglot-fsharp.el` even we have splitted up the package?

Would you mind to check/update to the latest `fsharp-mode` from melpa:

```
fsharp-mode-20210126.454
```
I could not reproduces this on a fresh Emacs installation using `(use-package fsharp-mode :ensure t)`

**Comment by jcs090218** [comment]
> Would you mind to check/update to the latest fsharp-mode from melpa:

I did it again and the error stills appear? I am not sure but I think we need to exclude the file `eglot-fsharp.el` while installing `fsharp-mode`? It's weird that we have already splitted up the package but the file `eglot-fsharp.el` still get included.

**Comment by juergenhoetzel** [comment]
> `fsharp-mode`? It's weird that we have already splitted up the package but the file `eglot-fsharp.el` still get included.

Indeed the [melpa recipe](https://github.com/melpa/melpa/blob/ccf97fe3676818a2f17f5647654690ee22055f82/recipes/fsharp-mode) needs to exclude this file. I'm preparing a PR.

**Comment by juergenhoetzel** [comment]
> [<img alt="@juergenhoetzel" width="20" height="20" src="https://avatars.githubusercontent.com/u/52547?s=60&amp;u=32272886d72a37b1e7ff444d63ba2b4f22aa5050&amp;v=4">](/juergenhoetzel) [juergenhoetzel](/juergenhoetzel) mentioned this issue [ yesterday ](#ref-pullrequest-793981962)
> [ Exclude eglot-fsharp (multiple packages repository) melpa/melpa#7389](/melpa/melpa/pull/7389)

melpa recipe is updated. But it seems we need a commit in this repo to trigger a melpa-update. 

I still can't understand why the `eglot-fsharp.el` is loaded automatically for you. Would you mind pasting a backtrace?

**Comment by jcs090218** [comment]
Ah.. It's gone now! :)

Thanks for fixing this! The only waning I have left is.

```
fsharp-mode.el:34:1:Warning: Package cl is deprecated
```

Close this now!
