### ISSUE TITLE
Is there an easy way to auto-indent the whole buffer?

### ISSUE THREAD

**Issue by mattiasdrp** [fsharp/emacs-fsharp-mode#290]
### Description

I'd like to `C-x h <tab>` to indent my buffer (or indent on save) but on this sample program nothing happens:

```fsharp
let printGreeting name =
let firstNumber = 2000 in
let secondNumber = 22 in
printfn $"The year is: {firstNumber + secondNumber}";
    printfn $"Hello {name} from F#!"
```

For OCaml I have the following lines:

```elisp
(use-package ocamlformat
  :hook
  (tuareg-mode . (lambda () (add-hook 'before-save-hook 'ocamlformat-before-save nil 'local)))
  )
```

That will apply ocamlformat anytime I save. 

Is there a corresponding package to do this in fsharp or some elisp shenanigans to have the same behaviour?

**Comment by mattiasdrp** [comment]
Why do I need this by the way? Because when following the tutorial ([here](https://docs.microsoft.com/en-us/learn/modules/fsharp-first-program/5-exercise-operators) for example), you're being asked to copy/paste some code but it will not be properly indented and currently I need to go on each line and hit `<tab>` to indent it properly because selecting the wrongly indented lines then hitting `<tab>` does nothing

**Comment by juergenhoetzel** [comment]
`eglot-fsharp` is currently broker for `fsac >= 0.59.2`.

https://github.com/fsharp/emacs-fsharp-mode/issues/331

Workaround: 
```elisp
(setq eglot-fsharp-server-version "0.59.2")
```

**Comment by razzmatazz** [comment]
fsautocomplete issue that is tracking this is https://github.com/fsharp/FsAutoComplete/issues/1087
