### ISSUE TITLE
Trying to include nuget reference breaks inferior buffer

### ISSUE THREAD

**Issue by elken** [fsharp/emacs-fsharp-mode#293]
### Description

Upon trying to call the `#r` extension against any nuget package, the entire inferior buffer breaks. I can still navigate around and input characters, so there's no blocking process; however I am unable to interact with the REPL process and all I can really do is kill and reopen the buffer

### Repro steps

Please provide the steps required to reproduce the problem

1. Create an inferior fsharp buffer (`run-fsharp`)

2. Run the following snippet

```fsharp
#r "nuget: Newtonsoft.Json";;
open Newtonsoft.Json;;

let o = {| X = 2; Y = "Hello" |};;

printfn "%s" (JsonConvert.SerializeObject o);;
```

Even just the following breaks:

```fsharp
#r "nuget: Newtonsoft.Json";;
```

### Expected behavior

Output similar to the below screenshot

![image](https://user-images.githubusercontent.com/2872862/161953133-6085145f-6327-4f40-9271-8f152462c627.png)

### Actual behavior

The buffer no longer becomes interactable.

### Known workarounds

None currently, I'm stumped.

### Related information 

* Operating system
![image](https://user-images.githubusercontent.com/2872862/161953304-8ce68070-4dd9-4e76-b280-dc230914b455.png)

* Branch
Pinned to commit c90d762c0692cc43032291d37b8ca3201c3d49bd

* Emacs version
28.0.91

* .NET Runtime, CoreCLR or Mono Version
![image](https://user-images.githubusercontent.com/2872862/161953559-78bc51e2-8a7d-4f00-8453-f00a0720678e.png)

* Performance information, links to performance testing scripts
Not relevant

**Comment by joanimato** [comment]
I'm running into this issue as well. I've tried it on two different macs, and strangely it works on one but not the other. Not sure why. Same versions of dotnet and emacs on both machines. 

I wonder if there's something else in my emacs config that breaks it...

**Comment by elken** [comment]
Good to see I'm not alone!

Did you get anywhere debugging it? @joanimato

**Comment by juergenhoetzel** [comment]
I have added `FSI` tests for this `fsx` file. All tests (also macos) pass: https://github.com/fsharp/emacs-fsharp-mode/pull/309

Would you mind to test it locally:
```bash
eldev -d test -f test/fsi-tests.el
```
Do you load the whole file via  <kbd>C-c C-f</kbd> (like the test case?)

**Comment by elken** [comment]
I ran it through `run-fsharp` in the inferior buffer, just tried on my linux machine (apparently I forgot to also check that...) and it actually works...

I'll re-run on the macbook shortly and report back

**Comment by elken** [comment]
Nope it does seem specific to macos, maybe it's M1 related?

**Comment by elken** [comment]
_how irksome_....
<img width="1621" alt="image" src="https://user-images.githubusercontent.com/2872862/174495171-fa9c632e-61b0-49e0-aca0-99224f7bd6b6.png">

**Comment by juergenhoetzel** [comment]
Integration tests use

```
dotnet --version
6.0.200
```

would you mind to test  this setup?

**Comment by elken** [comment]
Nix uses 
<img width="136" alt="image" src="https://user-images.githubusercontent.com/2872862/174495633-4f571a8c-ea76-4c5b-abc5-e83e6b866003.png">

Is there anything different in that minor release?

**Comment by juergenhoetzel** [comment]
> EDIT: Seems not

Thanks for your feedback: Does it work outside of emacs using:
```bash
dotnet fsi --readline-
```
?

**Comment by elken** [comment]
Yeah 
<img width="854" alt="image" src="https://user-images.githubusercontent.com/2872862/174496092-307920e9-01be-4c03-87b3-3abf330f21a7.png">

**Comment by juergenhoetzel** [comment]
just to narrow down the problem: I guess evaluating  in the `inferior fsharp` buffer
```lisp
(process-coding-system (get-buffer-process (current-buffer)))
```
returns:
```
(utf-8-unix . utf-8-unix)
```
`

**Comment by elken** [comment]
It does indeed :)

**Comment by juergenhoetzel** [comment]
Could you please use the following wrapper script:

```bash
#!/usr/bin/env bash

exec > >(tee /tmp/fsharpi-stdout.txt)
exec 2> >(tee /tmp/fsharpi-stderr.txt)
stdbuf -o 0 -e 0 dotnet fsi --readline-
```
as command instead of `dotnet fsi --readline-`
and upload the resulting files (as attachement).

**Comment by elken** [comment]
Here you go! :D

[fsharpi-stderr.txt](https://github.com/fsharp/emacs-fsharp-mode/files/8968993/fsharpi-stderr.txt)
[fsharpi-stdout.txt](https://github.com/fsharp/emacs-fsharp-mode/files/8968994/fsharpi-stdout.txt)

**Comment by juergenhoetzel** [comment]
Have you killed the interactive/hanging buffer after sending the test code? 
```
[Loading /tmp/nuget/4894--d262e99b-e7fc-4fd4-8ecf-421018e46ec0/Project.fsproj.fsx]
namespace FSI_0002.Project
``` 

is missing in your `stderr-file`.

**Comment by elken** [comment]
Oh I didn't run anything, I'm dumb...

**Comment by elken** [comment]
Running with the wrapper script seems to make it work?
![image](https://user-images.githubusercontent.com/2872862/175348036-166f39de-e8fe-426f-90c9-f08ba6e45b91.png)

**Comment by juergenhoetzel** [comment]
Fascinating. I guess it's related to `stdout/stderr` buffering. I guess using this wrapper will also work?

```bash
#!/usr/bin/env bash

stdbuf -o 0 -e 0 dotnet fsi --readline-
```

**Comment by juergenhoetzel** [comment]
> Yes that also works. Does this have a potential to be a fix upstream then?

Nope, I guess the root-cause is the emacs-side of the process. It currently uses a pipe `(eq process-connection-type nil)`:

Could you try redefining

```elisp

(defun fsharp-run-process-if-needed (&optional cmd)
  "Launch fsi if needed, using CMD if supplied."
  (unless (comint-check-proc inferior-fsharp-buffer-name)
    (setq inferior-fsharp-program
          (or cmd (read-from-minibuffer "fsharp toplevel to run: "
                                        inferior-fsharp-program)))
    (let ((cmdlist (inferior-fsharp-args-to-list inferior-fsharp-program))
          (process-connection-type 'pty))
      (with-current-buffer (apply (function make-comint)
                                  inferior-fsharp-buffer-subname
                                  (car cmdlist) nil
                                  (cdr cmdlist))
        (when (eq system-type 'windows-nt)
          (set-process-coding-system (get-buffer-process (current-buffer))
                                     'utf-8 'utf-8))
        (inferior-fsharp-mode))
      (display-buffer inferior-fsharp-buffer-name))))
      
```     
This should make `stdout` of `dotnet`  line-buffered.

**Comment by elken** [comment]
![image](https://user-images.githubusercontent.com/2872862/175380270-a0d97b85-848c-495a-914e-bf4dc6d694da.png)
LHS has the function redefined, RHS doesn't (and has the code pasted in and RET pressed, still stalls)

**Comment by juergenhoetzel** [comment]
Should be fixed by #311

**Comment by elken** [comment]
I'll make a note to test it tomorrow, thanks for a resolution! :D

**Comment by elken** [comment]
That looks to have done it! Brilliant :D
