### ISSUE TITLE
defunct with R type provider

### ISSUE THREAD

**Issue by t3476** [fsharp/emacs-fsharp-mode#33]
If source codes open R type provider module, it shows all R module name and keeps throwing deformed JSON and autocomplete defuncts everywhere when cursor locates.

Atom editor with fsharp works correctly. So I think it's not an issue of R type provider.

**Comment by rneatherway** [comment]
Thanks for reporting. Can you confirm which version of fsharp-mode you are using? If not the latest please try upgrading. If the latest, please post an example file and deformed JSON example so I can reproduce.

**Comment by t3476** [comment]
My code is just belows with fsproj referenced to R type provider. 

    module console
    open RProvider

    [<EntryPoint>]
    let main argv =
        printfn "%A" argv
        0 // return an integer exit code

Here is error message, each error corresponds to a R package, the rest is ignored because they're all similiar:
For information about GNU Emacs and the GNU system, type C-h C-a.
Loaded F# project 'console.fsproj'
error in process filter: fsharp-ac-filter-output: Wrong type argument: hash-table-p, (1)
error in process filter: Wrong type argument: hash-table-p, (1)
error in process filter: fsharp-ac-filter-output: Wrong type argument: hash-table-p, "ADGofTest"
error in process filter: Wrong type argument: hash-table-p, "ADGofTest"
error in process filter: fsharp-ac-filter-output: Wrong type argument: hash-table-p, "colorspace"
error in process filter: Wrong type argument: hash-table-p, "colorspace"
error in process filter: fsharp-ac-filter-output: Wrong type argument: hash-table-p, "copula"
error in process filter: Wrong type argument: hash-table-p, "copula"
error in process filter: fsharp-ac-filter-output: Wrong type argument: hash-table-p, "dichromat"
error in process filter: Wrong type argument: hash-table-p, "dichromat"
error in process filter: fsharp-ac-filter-output: Wrong type argument: hash-table-p, "digest"
error in process filter: Wrong type argument: hash-table-p, "digest"
...
user-error: Minibuffer window is not active


Here is malformed messages when I try to use point-complement

{\"Kind\":\"tooltip\",\"Data\":[[{\"Signature\":\"namespace RProvider\",\"Comment\":\"\"}]]}
{\"Kind\":\"info\",\"Data\":\"Background parsing started\"}
{\"Kind\":\"errors\",\"Data\":[]}
{\"Kind\":\"info\",\"Data\":\"Background parsing started\"}
{\"Kind\":\"errors\",\"Data\":[{\"FileName\":\"/home/t3485/FsProject/console/console.fs\",\"StartLine\":3,\"EndLine\":3,\"StartColumn\":6,\"EndColumn\":8,\"Severity\":\"Error\",\"Message\":\"The namespace or module 'RP' is not defined\",\"Subcategory\":\"typecheck\"}]}
{\"Kind\":\"info\",\"Data\":\"No tooltip information\"}
{\"Kind\":\"info\",\"Data\":\"Background parsing started\"}
{\"Kind\":\"errors\",\"Data\":[{\"FileName\":\"/home/t3485/FsProject/console/console.fs\",\"StartLine\":3,\"EndLine\":3,\"StartColumn\":6,\"EndColumn\":13,\"Severity\":\"Error\",\"Message\":\"The namespace or module 'RPvider' is not defined\",\"Subcategory\":\"typecheck\"}]}
{\"Kind\":\"info\",\"Data\":\"No tooltip information\"}
{\"Kind\":\"info\",\"Data\":\"Background parsing started\"}
{\"Kind\":\"errors\",\"Data\":[{\"FileName\":\"/home/t3485/FsProject/console/console.fs\",\"StartLine\":3,\"EndLine\":3,\"StartColumn\":6,\"EndColumn\":9,\"Severity\":\"Error\",\"Message\":\"The namespace or module 'RPv' is not defined\",\"Subcategory\":\"typecheck\"}]}
{\"Kind\":\"info\",\"Data\":\"No tooltip information\"}
{\"Kind\":\"info\",\"Data\":\"Background parsing started\"}
{\"Kind\":\"errors\",\"Data\":[{\"FileName\":\"/home/t3485/FsProject/console/console.fs\",\"StartLine\":3,\"EndLine\":3,\"StartColumn\":6,\"EndColumn\":8,\"Severity\":\"Error\",\"Message\":\"The namespace or module 'RP' is not defined\",\"Subcategory\":\"typecheck\"}]}
{\"Kind\":\"info\",\"Data\":\"No tooltip information\"}
{\"Kind\":\"info\",\"Data\":\"Background parsing started\"}
{\"Kind\":\"errors\",\"Data\":[]}
{\"Kind\":\"tooltip\",\"Data\":[[{\"Signature\":\"namespace RProvider\",\"Comment\":\"\"}]]}
{\"Kind\":\"info\",\"Data\":\"Background parsing started\"}
{\"Kind\":\"errors\",\"Data\":[{\"FileName\":\"/home/t3485/FsProject/console/console.fs\",\"StartLine\":3,\"EndLine\":4,\"StartColumn\":17,\"EndColumn\":1,\"Severity\":\"Error\",\"Message\":\"Incomplete structured construct at or before this point in open declaration\",\"Subcategory\":\"parse\"}]}
{\"Kind\":\"error\",\"Data\":\"Timed out while fetching completions\"}
{\"Kind\":\"info\",\"Data\":\"Background parsing started\"}
{\"Kind\":\"errors\",\"Data\":[{\"FileName\":\"/home/t3485/FsProject/console/console.fs\",\"StartLine\":3,\"EndLine\":4,\"StartColumn\":17,\"EndColumn\":1,\"Severity\":\"Error\",\"Message\":\"Incomplete structured construct at or before this point in open declaration\",\"Subcategory\":\"parse\"}]}
{\"Kind\":\"tooltip\",\"Data\":[[{\"Signature\":\"namespace RProvider\",\"Comment\":\"\"}]]}
)."
user-error: Minibuffer window is not active [2 times]

**Comment by rneatherway** [comment]
Are you definitely running the latest fsharp-mode from MELPA? Please also post the fsproj you are using so I can try to reproduce here.

**Comment by t3476** [comment]
I was using 20151020. I updated it to latest 20151024 and tried again but the problems remain.
I post how the project is generated instead because it's easier than reproducing problem from fsproj.

The project I tested is just simplest project generated by yeoman fsharp generator, step is belows:

    yo fsharp

choose standalone console app with paket.
change directory into generated project.

    mono .paket/paket.exe add nuget RProvider

create a file named `paket.references` with  only one line content `RProvider`

    mono .paket/paket.exe update

That's all. edit any *.fs with emacs can reproduce the issues

**Comment by rneatherway** [comment]
> The project I tested is just simplest project generated by yeoman fsharp generator, step is belows:

How should I install this? I've not used it and `npm install -g generator-fsharp` tries to install things under `/usr` which I'm not interested in.

**Comment by t3476** [comment]
Nevermind. Please ignore those step, I should upload the project at begining.
https://drive.google.com/file/d/0B7vBrbZs1TVhUHV6SmhFOW0zQ0k/view?usp=sharing

**Comment by rneatherway** [comment]
Thanks, I've tried your project locally without any problems, so I'm not sure what is different at your end. Your project didn't include any reference to the R type provider so I added a line `open RProvider`, which didn't cause any problems either. I don't understand where the output you sent is coming from:

```
error in process filter: fsharp-ac-filter-output: Wrong type argument: hash-table-p, (1)
error in process filter: Wrong type argument: hash-table-p, (1)
error in process filter: fsharp-ac-filter-output: Wrong type argument: hash-table-p, "ADGofTest"
error in process filter: Wrong type argument: hash-table-p, "ADGofTest"
error in process filter: fsharp-ac-filter-output: Wrong type argument: hash-table-p, "colorspace"
error in process filter: Wrong type argument: hash-table-p, "colorspace"
```

I couldn't find ADGofTEST or colorspace anywhere in your project so I have no idea how that is happening. I don't have R installed either. I need explicit instructions as to how this happens please.

**Comment by t3476** [comment]
I hope belows are explicit enough because my instructions is not suitable everywhere.
You have to install R in order to reproduce problem.
`ADGofTEST` and `colorspace` are R packages, R type provider parses them and create corresponding F# modules. Those problems started when RProvider find libR.so and starts parsing R packages.
I don't encounter those outputs either when R is uninstalled.

**Comment by rneatherway** [comment]
Are you using Windows? I cannot reproduce on Linux, or I don't know how to use the R type provider. This is likely because I have never used it before. To reproduce I need precise step by step instructions.

Alternatively can you please eval `(setq fsharp-ac-debug 2)` cause the error to happen again and then post the contents of the buffer `*fsharp-debug*` here?

**Comment by t3476** [comment]
I'll try to provide exact instructions later, I have to think about how to set up an evironment on other linux. I'm using arch linux here. 
I don't see any thing useful in debug messages. It just shows a lot of R package name. 

1446044656.7804408: project "/home/t3485/FsProject/console/console.fsproj"
1446044657.6690195: {"Kind":"project","Data":{"Project":"/home/t3485/FsProject/console/console.fsproj","Files":["/home/t3485/FsProject/console/console.fs"],"Output":"/home/t3485/FsProject/console/bin/Debug/console.exe","References":["packages/DynamicInterop/lib/net40/DynamicInterop.dll","/usr/lib/mono/gac/FSharp.Core/4.3.1.0__b03f5f7f11d50a3a/FSharp.Core.dll","packages/R.NET.Community.FSharp/lib/net40/RDotNet.FSharp.dll","packages/R.NET.Community/lib/net40/RDotNet.NativeLibrary.dll","packages/R.NET.Community/lib/net40/RDotNet.dll","packages/RProvider/lib/net40/RProvider.Runtime.dll","packages/RProvider/lib/net40/RProvider.dll","/usr/lib/mono/4.5/System.Core.dll","/usr/lib/mono/4.5/System.Numerics.dll","/usr/lib/mono/4.5/System.dll","/usr/lib/mono/4.5/mscorlib.dll"]}}

1446044657.6693363: Received 'project' message of length 65
1446044658.0104017: Parsing "/home/t3485/FsProject/console/console.fs"
1446044659.2665915:  [1] "ADGofTest"    "colorspace"   "copula"       "dichromat"    "digest"      

1446044659.9850085: "ADGofTest"    "colorspace"   "copula"       "dichromat"    "digest"      

1446044700.2288506: Parsing "/home/t3485/FsProject/console/console.fs"
1446044700.2294614: tooltip "/home/t3485/FsProject/console/console.fs" 2 7 400
1446044700.3149924:    "colorspace"   "copula"       "dichromat"    "digest"      

1446044700.8239224:   "copula"       "dichromat"    "digest"      

1446044703.3292458: Parsing "/home/t3485/FsProject/console/console.fs"
1446044703.3297918: tooltip "/home/t3485/FsProject/console/console.fs" 2 8 400
1446044703.3440027:       "dichromat"    "digest"      

1446044703.7407186:    "digest"      

1446044707.2746134: Parsing "/home/t3485/FsProject/console/console.fs"
1446044707.2750635: tooltip "/home/t3485/FsProject/console/console.fs" 2 15 400
1446044707.2962887:      

1446044707.8022363: "doParallel"   "foreach"      "ggplot2"      "gridBase"     "gsl"         

1446044707.8828504:   "foreach"      "ggplot2"      "gridBase"     "gsl"

**Comment by rneatherway** [comment]
The text that Emacs is receiving is just wrong here. Everything it receives should be a JSON message like:

```
1446046496.7956703: {"Kind":"tooltip","Data":[[{"Signature":"val main : argv:string [] -> int\n\nFull name: console.main","Comment":""}]]}

1446046496.7957373: Received 'tooltip' message of length 65
```

As you can see this happened in your case with the `project` message, but not after that. If you keep waiting do you eventually see the next JSON message?

I suspect this may be because FSharp.Compiler.Service is outputting to standard out. You could test that by compiling your own version with `let diagnosticsLog = ref (Some stdout)` changed to `let diagnosticsLog = ref None`  in `src/absil/ildiag.fs` and copying it into the fsautocomplete directory.

A simpler way to check exactly what the output is would be to run fsautocomplete.exe standalone like:

```
mono fsautocomplete.exe
project "/home/t3485/FsProject/console/console.fsproj"
parse "/home/t3485/FsProject/console/console.fs" sync
<paste the contents of console.fs>
<<EOF>>
tooltip "/home/t3485/FsProject/console/console.fs" 2 7 400
```

And post everything that is output to here.

**Comment by rrottier** [comment]
I have very similar issues. 

My setup:
* OS: OSX 10.10.5
* Install Fslab basic journal template as per the instructions: http://fslab.org/download/
* Use spacemacs, installed as per instructions with fsharp layer enabled
* Use mono provided by homebrew
* create a file with

` #load "packages/FsLab/FsLab.fsx" `

Error
```
Loaded F# project 'FsLab.Tutorial.fsproj'
error in process filter: fsharp-ac-filter-output: Wrong type argument: hash-table-p, (1)
error in process filter: Wrong type argument: hash-table-p, (1)
error in process filter: fsharp-ac-filter-output: Wrong type argument: hash-table-p, "base"
error in process filter: Wrong type argument: hash-table-p, "base"
error in process filter: fsharp-ac-filter-output: Wrong type argument: hash-table-p, "boot"
error in process filter: Wrong type argument: hash-table-p, "boot"
```

**Comment by rneatherway** [comment]
I've just tried to reproduce on Linux, but I guess my R installation isn't quite right. How did you install R? You didn't have to compile the 64-bit version like it says here: http://bluemountaincapital.github.io/FSharpRProvider/mac-and-linux.html ?

**Comment by t3476** [comment]
I don't need to build it because most of the linux distributions, including Fedora and Archlinux, have mono 64-bit version by default. That page is somewhat outdated. 
I just install mono and R by linux package manager, build fsharp from source, then run below line to get it work
    echo MONO64=$MONO_PREFIX/bin/mono > ~/.rprovider.conf

**Comment by t3476** [comment]
I tried mono fsautocomplete.exe.  output is attached.
[error.txt](https://github.com/fsharp/emacs-fsharp-mode/files/33281/error.txt)

**Comment by rneatherway** [comment]
> echo MONO64=$MONO_PREFIX/bin/mono > ~/.rprovider.conf

OK, I didn't know about this, reproduced now.

```
~/dev/other/fslab/FsLab.Templates-basic $ mono ~/dev/other/FsAutoComplete/FsAutoComplete/bin/Debug/fsautocomplete.exe
parse "test.fsx"
#load "packages/FsLab/FsLab.fsx"
<<EOF>>
 [1] "base"       "boot"       "class"      "cluster"    "codetools" 
 [6] "compiler"   "datasets"   "foreign"    "graphics"   "grDevices" 
[11] "grid"       "KernSmooth" "lattice"    "MASS"       "Matrix"    
[16] "methods"    "mgcv"       "nlme"       "nnet"       "parallel"  
[21] "rpart"      "spatial"    "splines"    "stats"      "stats4"    
[26] "survival"   "tcltk"      "tools"      "utils"     
{"Kind":"info","Data":"Background parsing started"}
{"Kind":"errors","Data":[]}
```

It looks like it is R itself that is writing to standard out (http://stackoverflow.com/questions/9689104/installing-r-on-mac-warning-messages-setting-lc-ctype-failed-using-c). We have to stop it from doing this because it is being interleaved with the data stream sent by FsAutoComplete.

**Comment by rneatherway** [comment]
Perhaps the R type provider could redirect the subprocess' standard out to /dev/null or similar.

**Comment by tpetricek** [comment]
@t3476 It's great to hear that manly Linux distros now come with 64 bit mono. Could you perhaps send a PR to add this information to the documentation? What is the best way to check whether one has 64 bit mono already? The page is here: https://github.com/BlueMountainCapital/FSharpRProvider/blob/master/docs/content/mac-and-linux.fsx (I'll be happy to check or fix the English, if you can provide the content!)

**Comment by tpetricek** [comment]
The new version of R provider (1.5.15) disables auto print in R.NET which might have been causing this (although I'm not 100% sure - I disabled it because it was causing another issue).

Can you please check if this is still happening in 1.5.15?

**Comment by t3476** [comment]
I have no idea what additional information can be provided to documents. Its usage is almost the same to how other libraries are used excepts an additional file ~/.rprovider.conf.

I tried the latest RProvider 1.1.15 with a clean new project, the problem still exists.

**Comment by tpetricek** [comment]
@t3476 I guess we just need to add a note saying that people do not need to compile mono if they already have 64 bit version installed.

Hmm, thanks for checking with the 1.1.15 version. Will further investigate what's going on!

**Comment by rneatherway** [comment]
It fixes the problem for me. Make sure you've restarted Emacs or at least fsautocomplete to pick up the new version of the type provider. Thanks for investigating @tpetricek.

**Comment by t3476** [comment]
Sorry for wrong informations. This issue is solved.
My problem is not caused by RProvider now, R intepreter is throwing some warning to fsautocomplete.exe because of other misconfiguration.  Thanks for helps.

**Comment by tpetricek** [comment]
I'm still a bit puzzled why this would be happening (because R runs in a separate process!) but glad that the latest release makes it (at least) work better! :-)
