### ISSUE TITLE
fsac >= 0.59.3: No typecheck results

### ISSUE THREAD

**Issue by juergenhoetzel** [fsharp/emacs-fsharp-mode#331]
### Description

`eglot`  `flycheck/xref` fails for `fsac`>= 0.59.3

### Repro steps

Please provide the steps required to reproduce the problem

```bash
eldev -dtT test 
```

### Expected behavior

Integreation tests succeed

### Actual behavior

integrations checks timeout (waiting for typecheck results).

### Workaround

Pin to older version succeds:

```bash
eldev -S '(setq eglot-fsharp-server-version "0.59.2")' -dtT test 
```

**Comment by juergenhoetzel** [comment]
@razzmatazz would you mind to take a look?

I suspect this is related to:

https://github.com/fsharp/FsAutoComplete/pull/1084

**Comment by razzmatazz** [comment]
> @razzmatazz would you mind to take a look?
> 
> I suspect this is related to:
> 
> [fsharp/FsAutoComplete#1084](https://github.com/fsharp/FsAutoComplete/pull/1084)

taking a look.. sorry for breaking stuff

**Comment by razzmatazz** [comment]
hmm, it looks like to be something else -- `main` branch on fsautocomplete fails with "no typecheck results" for me too, but my commit did not -- will do git bisect..

**Comment by razzmatazz** [comment]
git bisect points me to this as bad commit:
```
ed061e685ef6b5bd41a83c4b8808e86d7753780c is the first bad commit
commit ed061e685ef6b5bd41a83c4b8808e86d7753780c
Author: Jimmy Byrd <jimmybyrd@gmail.com>
Date:   Sun Mar 19 16:37:12 2023 -0400

    Only reload projects that need and populate test runner (#1082)
    
    Co-authored-by: Chet Husk <chusk3@gmail.com>
```

I registered https://github.com/fsharp/FsAutoComplete/issues/1087

**Comment by razzmatazz** [comment]
> taking a look.. sorry for breaking stuff

I am retracting my apologies :D

**Comment by juergenhoetzel** [comment]
:rocket:  thanks a lot for the detailed analysis!

> > taking a look.. sorry for breaking stuff
> 
> I am retracting my apologies :D

and sorry for suspecting you to be responsible for this 🙇

**Comment by TheAngryByrd** [comment]
It's me, I'm always responsible for it 😂
