### ISSUE TITLE
Add licence

### ISSUE THREAD

**Issue by kjnilsson** [fsharp/emacs-fsharp-mode#36]
hi - I noticed you don't have a licence file. Neither does vim-fsharp - we should probably add one but which one - apache?

**Comment by rneatherway** [comment]
Good point, and yes I would agree with Apache. That's in line with the other tools in here.

**Comment by dgellow** [comment]
How does it work if you want to add a license after the beginning of a project? Do you have to ask every past contributors to accept the change?
I'm just curious.

**Comment by rneatherway** [comment]
Yes we had to do that for FAKE, required around 100 people to say yes. However, this project was under Apache previously, we just forgot to copy the license over when we split the old repo: `https://github.com/fsharp/fsharpbinding/blob/master/LICENSE.md`.
