### ISSUE TITLE
Symbol usage highlighting overlays should not grow when typing

### ISSUE THREAD

**Issue by rneatherway** [fsharp/emacs-fsharp-mode#37]

**Comment by rneatherway** [comment]
Specifically when typing at one end, or inside them. In the last case they should probably be removed.

**Comment by joncfoo** [comment]
Perhaps this could lead to a new feature: rename symbol along with its usages

**Comment by rneatherway** [comment]
The current implementation only gets usages in the current file, so it would need some work in FsAutoComplete.

**Comment by rneatherway** [comment]
Fixed by #79
