### ISSUE TITLE
README needs updating since the dissolution of "fsharpbinding"

### ISSUE THREAD

**Issue by SamB** [fsharp/emacs-fsharp-mode#38]
Foremost among the stale material is the [Manual Installation](https://github.com/fsharp/emacs-fsharp-mode#manual-installation) section, but that isn't the *only* place that still refers to either the old directory structure or the old repository.

**Comment by rneatherway** [comment]
Could you take a look at #40 and let me know if that fixes everything you saw please?

**Comment by rneatherway** [comment]
OK, assuming it did.
