### ISSUE TITLE
failing on Linux: Debugger entered--Lisp error: (void-function -any)

### ISSUE THREAD

**Issue by ks** [fsharp/emacs-fsharp-mode#44]
Hi, 

I'm getting this error on Arch Linux (x86-64, kernel 4.2.5-1-ARCH)  (using both package from MELPA as well as compiling from repository) when opening buffer with F# code.

Emacs has version 24.5.1.

When compiling from repository, I did "make test-all" - worked fine (0 errors).

Full emacs stacktrace looks like:

```
Debugger entered--Lisp error: (void-function -any)
  (-any (function fsharp-mode--executable-find) (quote ("fsharpc" "fsc")))
  (defvar fsharp-compile-command (-any (function fsharp-mode--executable-find) (quote ("fsharpc" "fsc"))) "The program used to compile F# source files.")
  eval-buffer(#<buffer  *load*> nil "/home/x/.emacs.d/fsharp-mode/fsharp-mode.el" nil t)  ; Reading at buffer position 1460
  load-with-code-conversion("/home/x/.emacs.d/fsharp-mode/fsharp-mode.el" "/home/x/.emacs.d/fsharp-mode/fsharp-mode.el" nil t)
  fsharp-mode()
  set-auto-mode-0(fsharp-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer fstest.fs> "~/projects/fstest/fstest.fs" nil nil "~/projects/fstest/fstest.fs" (7344474 2051))
  find-file-noselect("~/projects/fstest/fstest.fs" nil nil t)
  find-file("~/projects/fstest/fstest.fs" t)
  call-interactively(find-file nil nil)
  command-execute(find-file)
```

Fsharp compiler and interpreter are on standard location:

/usr/bin/fsharpc
/usr/bin/fsharpi
/usr/bin/fsharpiAnyCpu

The error originates from fsharp-mode.el:

(defvar fsharp-compile-command
  (-any #'fsharp-mode--executable-find '("fsharpc" "fsc"))
  "The program used to compile F# source files.")

Does anybody know if fsharp-mode works on Linux and/or how to make the mode work?

Cheers,
  Karol

**Comment by rneatherway** [comment]
I suggest that you check that your dash.el is up to date, see https://github.com/fsharp/emacs-fsharp-mode#void-function--any-or-similar

**Comment by ks** [comment]
That was it, thank you. 

Cheers,
  Karol
