### ISSUE TITLE
Company mode

### ISSUE THREAD

**Issue by nosami** [fsharp/emacs-fsharp-mode#47]
Would you accept a PR to add company mode for autocomplete? I'd be happy to do the work.

**Comment by rneatherway** [comment]
Would you like to replace the use of the `autocomplete` package? I've thought about it myself, but haven't found the time. I think company mode is better, and use it myself in other modes, so I would be very happy if you sent such a PR. One thing I'm not sure about though, is whether it's possible to display helptext in completions using a popup like I do at the moment (with `pos-tip`).

**Comment by nosami** [comment]
I was thinking of having a configurable option to switch it on, but I could replace it if you'd prefer. I use company-mode everywhere else too. It's the default in spacemacs.

company-mode supports documentation with the use of the F1 key

**Comment by rneatherway** [comment]
I'm fine with removing autocomplete, or making it configurable. I just found this package that allows the 'pos-tip on idle' behaviour, which I quite like: https://github.com/expez/company-quickhelp.

**Comment by nosami** [comment]
Nice find! I'll probably remove autocomplete then. Should be simpler.

**Comment by nosami** [comment]
One thing to consider - autocomplete-mode comes out of the box with a stock emacs install, but company-mode doesn't.

**Comment by rneatherway** [comment]
Right, I'm fine with that. We can just add company-mode to the package dependencies so it gets pulled in if necessary when installing from MELPA. If people install manually, then they already have to get `s` and `dash`.

**Comment by nosami** [comment]
Heh...it might not be today. My electricity just went off!

Right, I'm fine with that. We can just add company-mode to the package
dependencies so it gets pulled in if necessary when installing from MELPA.
If people install manually, then they already have to get s and dash.

—
Reply to this email directly or view it on GitHub
<https://github.com/fsharp/emacs-fsharp-mode/issues/47#issuecomment-167579898>
.

**Comment by rneatherway** [comment]
Bad luck! No worries.

**Comment by juergenhoetzel** [comment]
I use `auto-complete`. I guess most GNU/Emacs users do. I would prefer to make configurable.

**Comment by rneatherway** [comment]
Hi @juergenhoetzel. Given that `fsharp-mode` sets up `auto-complete` at the moment transparently to the user, how would it affect you if it was switched to use `company` instead? Is it the visual difference, the capabilities of the two packages, or some custom configuration you have?

**Comment by juergenhoetzel** [comment]
@rneatherway I'm just used to the    `auto-complete` key-bindings/setup. According to the *MELPA* download stats i suspect the majority of Emacs users still prefer `auto-complete`.

IMHO the best option would be to provide support for both completion packages like most other Emacs packages do.

**Comment by nosami** [comment]
I've already started removing auto-complete on my [PR](https://github.com/fsharp/emacs-fsharp-mode/pull/49). I really don't mind putting it back, it shouldn't take too long.

There really aren't any keybindings to learn as the popup appears automatically. The main thing to consider I think is that supporting both will make the code a little more complex.

**Comment by rneatherway** [comment]
From the MELPA stats it looks fairly close (160k to 130k), and auto-complete is quite a bit older so it doesn't surprise me that it has more. Most other languages provide a separate package that just does completions, but fsharp-mode provides an "all-in-one" experience with tooltips and everything else as well. If it's easy then let's try to keep support for both. Based on how the company support looks so far (generally smoother) I will probably make it the default. autocomplete-mode has been pretty much unsupported for a long time and generally hellish to work with. I would much rather integrate with an active project that has bugfixes and improvements being added to it.

**Comment by nosami** [comment]
I was thinking that if both company-mode and auto-complete mode were to be available, then I should move those parts into separate files + one common and just `require` the appropriate one

**Comment by juergenhoetzel** [comment]
+1 for splitting the completion code from the major mode. Merlin/OCaml also splitted the completion code in two seperate packages last year.

@rneatherway Why is autocomplete-mode unspported/inactive? Its under active development on github.

**Comment by nosami** [comment]
@juergenhoetzel [a good read](https://github.com/company-mode/company-mode/issues/68) 

Also, I've dealt directly with @dgutov before and he's been extremely responsive to my questions (even the stupid ones!) 

From a user's perspective, I think company-mode is nicer to use. From a backend devs point of view, the API is much nicer.

**Comment by nosami** [comment]
@juergenhoetzel Also there are numerous reported issues with pos-tip (the docstring overlay) that don't seem to get fixed.

**Comment by rneatherway** [comment]
> +1 for splitting the completion code from the major mode. Merlin/OCaml also splitted the completion code in two seperate packages last year.

What about the non-completion parts of intellisense? These include tooltips and symbol usage and also require the backend process to be available. However, they aren't tied to a completion engine. It isn't clear how best to separate out these parts.

> @rneatherway Why is autocomplete-mode unspported/inactive? Its under active development on github.

It is now under some kind of development on github (around 20 non-merge commits last year) after a long period of complete dormancy (I'm talking about past 5/6 years). This is quite a contrast.

> @juergenhoetzel Also there are numerous reported issues with pos-tip (the docstring overlay) that don't seem to get fixed.

This is also a good point. On Mac and Windows pos-tip has quite a few bugs (flickering, wrong location, slow), while the company overlay seems to work much better at least on Mac. I have to admit that I haven't tried it on Windows.

**Comment by nosami** [comment]
When I was talking about splitting the files up, I wasn't talking about separate packages to be clear.

**Comment by rneatherway** [comment]
> When I was talking about splitting the files up, I wasn't talking about separate packages to be clear.

Right, I understood that, and was also thinking about it. I think it makes sense.

**Comment by dgutov** [comment]
Hi all, I'd like to correct some misconceptions.

> One thing to consider - autocomplete-mode comes out of the box with a stock emacs install, but company-mode doesn't.

It really doesn't, and never will (if only for copyright reasons). On the other hand, company-mode probably will, one day.

> Why is autocomplete-mode unspported/inactive? Its under active development on github.

Look closer at the commit log: the last change of any substance was last January. At some point, auto-complete's author tried initiating a rewrite (auto-complete2, it even [has a repo](https://github.com/auto-complete/auto-complete2)), but that never went anywhere. So now it's passed to Yoshida, basically for maintenance.

To be fair, I've also been busy with mostly other stuff at least for the last year, but it still seems company-mode changed more in that period.

> Also there are numerous reported issues with pos-tip (the docstring overlay) that don't seem to get fixed.

You probably mean [popup.el](https://github.com/auto-complete/popup-el). pos-tip uses a chromeless frame, not overlays, but of course it has its own problems.

**Comment by nosami** [comment]
@dgutov thanks for the corrections!

**Comment by rneatherway** [comment]
> It really doesn't, and never will (if only for copyright reasons). On the other hand, company-mode probably will, one day.

Yes, I should have pointed that out. I really hope company gets in one day so that we have a canonical solution.

> You probably mean popup.el. pos-tip uses a chromeless frame, not overlays, but of course it has its own problems.

I wrote `fsharp-mode` to use pos-tip for preference, but to also be able to use popup.el, the default for auto-complete. I use this on OSX because of the issues with pos-tip. company-quickhelp seems more robust though.

**Comment by dgutov** [comment]
> I really hope company gets in one day so that we have a canonical solution.

I'm probably the main person holding that off. :persevere: There's cruft in company-mode, and there's cruft in minibuffer.el, and `company-capf` doesn't support a couple of things that native backends do... I'd really like everything to be better if we want to make it canonical.

> company-quickhelp seems more robust though.

That's possible (the author has tweaked the code for a while), but it still uses pos-tip under the covers.

**Comment by rneatherway** [comment]
#49
