### ISSUE TITLE
Symbol's function definition is void: -any

### ISSUE THREAD

**Issue by userzimmermann** [fsharp/emacs-fsharp-mode#5]
Hi. Already posted as https://github.com/fsharp/fsharpbinding/issues/1013 and then found this repo.

Is this repo the better place for emacs related issues?

**Comment by rneatherway** [comment]
Yes, this is the right place, the other repo is deprecated.

How did you install. In particular you need an up to date version of `dash`. I suggest just upgrading all your packages and trying again.

**Comment by obadz** [comment]
Upgrading dash/dash-functional to latest versions did it for me! Thanks @rneatherway

**Comment by userzimmermann** [comment]
@rneatherway @obadz Thanks :) The actual problem in my case was that my Debian's outdated **dash-el** package was loaded first, although later in `load-path`, but maybe via the **silversearcher-ag-el** Debian package. I removed both (and installed **ag** via `package-install`) and now everything works fine.

**Comment by obadz** [comment]
@userzimmermann join me on NixOS :)

**Comment by userzimmermann** [comment]
@obadz I'm trying to get NixOS/Guix running on Cygwin. Got quite far. Was some weeks ago. Can't remember the remaining issue. Thought about eventually creating Chocolatey packages. Need some time to continue... Any experience with that topic?

**Comment by obadz** [comment]
I'm afraid I have no experience with NixPkgs on Windows but I've got a decent chunk of the F# world packaged in it and running nicely on Linux :)

https://github.com/NixOS/nixpkgs/pull/7955

**Comment by userzimmermann** [comment]
@obadz Forked and will take a look at it soon...
