### ISSUE TITLE
Comment highlighting interferes with code past (*) overload

### ISSUE THREAD

**Issue by SjorsVanGelderen** [fsharp/emacs-fsharp-mode#51]
When overloading the ```(*)``` operator everything after the first ```(*``` becomes a comment, because the matching ```*)``` sequence is never encountered.
![Uploading Screenshot from 2016-01-12 09-34-58.png…]()

**Comment by rneatherway** [comment]
Let me know how you get on with #51

**Comment by rneatherway** [comment]
Any luck?

**Comment by rneatherway** [comment]
Closed by #52.
