### ISSUE TITLE
Tooltip doesn't use theme after window reaches a certain size...

### ISSUE THREAD

**Issue by simendsjo** [fsharp/emacs-fsharp-mode#54]
I only use Emacs (Spacemacs) for fsharp scripts, but I have an annoying issue where the tooltips revert to using plain X11 colors after the window reaches a certain size. I have no idea whether this is due to pos-tip, fsharp-mode, emacs or my setup. I already [asked](http://emacs.stackexchange.com/questions/19167/spacemacs-not-using-the-theme-for-tooltips-after-resizing-the-window) on stackexchange a month ago, but there are no answers that could even point me in the right correction for where to report a bug.

If this is probably a pos-tip issue, I'll try to file a bug against that plugin instead.

**Comment by nosami** [comment]
The [company mode PR](https://github.com/fsharp/emacs-fsharp-mode/pull/49) should fix this issue.

**Comment by simendsjo** [comment]
Thanks! Good to know. If you find the time, answer the question I linked for 50 stackexchange points :)

**Comment by rneatherway** [comment]
What he said :-) I hope we should get that merged pretty soon and I will rerelease on MELPA. I think your problems are likely down to pos-tip which is basically unmaintained.

**Comment by nosami** [comment]
@simendsjo I tested the company mode PR on archlinux and i3wm on a HiDPI screen, so I know it works fine there :)

**Comment by simendsjo** [comment]
Should this work for `fsharp-ac/show-tooltip-at-point` too?

**Comment by rneatherway** [comment]
That uses `pos-tip` directly. I think this is the version that you get from MELPA: https://github.com/pitkali/pos-tip so best to file an issue there if you're still having trouble.

**Comment by simendsjo** [comment]
@nosami mentioned that the PR to company mode should fix this. I thought I got that update which is why I'm asking.

**Comment by rneatherway** [comment]
Yes, I understand. That PR didn't change the way that `fsharp-ac/show-tooltip-at-point` works, so I think this must be a pos-tip issue.

**Comment by nosami** [comment]
Yeah, I misunderstood originally. I thought you were talking about the intellisense tooltip popup. 

Is this what you mean? 
<img width="448" alt="screen shot 2016-02-06 at 21 23 50" src="https://cloud.githubusercontent.com/assets/667194/12869454/12842374-cd18-11e5-9027-f0f1aabb3e7f.png">

**Comment by simendsjo** [comment]
@nosami: Yes, that one :)

**Comment by nosami** [comment]
Can't say I'm fond of the colours, but it looks the same at all window widths for me.

**Comment by simendsjo** [comment]
![bad](https://cloud.githubusercontent.com/assets/351519/12869613/ed363352-cd24-11e5-8536-59b812875222.png)
![nice](https://cloud.githubusercontent.com/assets/351519/12869612/ed3528c2-cd24-11e5-8c82-30612f309e10.png)

**Comment by simendsjo** [comment]
Oh... Autoscaling.. The second image is how it appears if the window starts small before I resize it, the first image is after the window has reached some larger size.

**Comment by nosami** [comment]
Do you have this setting switched off?

<img width="643" alt="screen shot 2016-02-06 at 22 21 03" src="https://cloud.githubusercontent.com/assets/667194/12869747/fc499578-cd1f-11e5-991e-4d697e7b29f1.png">

The black and white tooltip is a native GTK tooltip, whereas the solarized themed one is an overlay popup rendered by emacs.

Changing this setting for me makes the tooltips display the same colour as the completion tooltips

<img width="521" alt="screen shot 2016-02-06 at 22 23 48" src="https://cloud.githubusercontent.com/assets/667194/12869763/60204588-cd20-11e5-95a2-4ab7594dda70.png">

**Comment by nosami** [comment]
Looking at the generated code, this is equivalent to `(setq x-gtk-use-system-tooltips nil)`

**Comment by simendsjo** [comment]
Thanks! That works and looks a lot better, but I find it strange that the behavior was somehow bound to the window size.

**Comment by nosami** [comment]
Yes, very :)

**Comment by rneatherway** [comment]
This seems to be resolved.
