### ISSUE TITLE
Tramp support

### ISSUE THREAD

**Issue by juergenhoetzel** [fsharp/emacs-fsharp-mode#57]
Would you accept a PR to add Tramp support for remote editing? Requires:

1. Use ```start-file-process``` instead of ```start-process```
2. Handle multiple completion processes
3. Dissect ```buffer-file-name``` before passing commands to the completion process  
4. Convert filenames back to tramp filenames when receiving responses from the completion process

**Comment by rneatherway** [comment]
Wow that would be pretty cool. Wouldn't it require bringing all the files in the project over locally though so that fsautocomplete can find them?

**Comment by juergenhoetzel** [comment]
The ```fsautocomplete``` process will be started on the remote host by ```start-file-process``` which is already tramp-aware. ```fsharp-mode``` would have to keep track of relation between ```fsharp-mode``` buffers and their corresponding ```fsautocomplete``` process.

I thought of makeing ```fsharp-ac-completion-process``` an alist instead of a single value containing the ```fsautocomplete``` process. 

For example, when having a local and a remote/tramp ```fsautocomplete``` process:

```((nil . #<process fsharp-complete>) ("/ssh:juergen@myhost.domain:" . #<process fsharp-complete-2>))```

This is inspired by [rtags](https://github.com/Andersbakken/rtags), a nice c++  indexer, which is already tramp-aware.

**Comment by rneatherway** [comment]
Wow! I didn't know there was support for that. It does assume that you have mono on the remote host. Do you also copy over `fsautocomplete`? It sounds plausible. I would definitely accept a working patch as long as the local mode isn't affected negatively.

**Comment by juergenhoetzel** [comment]
I assumed  ```tramp```Users would adjust  ```tramp-remote-path ```  and setup ```fsautocomplete``` for themselves. A hint (if it's not found on the remote host) would be a  sufficient advice  for a typical Emacs user.

To copy over ```fsautocomplete```would be a option but will make the code more complicated/error-prone.

**Comment by rneatherway** [comment]
OK, with documentation sounds fine to me.

**Comment by juergenhoetzel** [comment]
Thanks for your feedback. I will setup a ```tramp``` branch in the coming days.

**Comment by rneatherway** [comment]
Wonderful, I look forward to the feature!

**Comment by juergenhoetzel** [comment]
Jason started the "screecast thing" :smile: 
![fsharp-tramp](https://cloud.githubusercontent.com/assets/52547/14060109/4f9935bc-f359-11e5-9d22-7aa6116866a2.gif)

You can now edit _multiple projects_ on _multiple hosts_.

**Comment by nosami** [comment]
This looks amazing! A gif is worth a thousand words etc :)

**Comment by rneatherway** [comment]
Sorry I lost track of this one. It seems it conflicts now, but hopefully trivially. Would you mind merging/rebasing and I'll get it in and release?

**Comment by juergenhoetzel** [comment]
No worries. I will rebase.

**Comment by juergenhoetzel** [comment]
I just rebased. https://github.com/fsharp/emacs-fsharp-mode/pull/66

**Comment by rneatherway** [comment]
Great, merged.
