### ISSUE TITLE
auto-identation issue when try to save file

### ISSUE THREAD

**Issue by flypixel** [fsharp/emacs-fsharp-mode#59]
This code: 
```f#
let a =
    seq {
        while true do
        	yield  1
    }
```
after saving becomes (C-x C-s):
```f#
let a =
    seq {
        while true do
        yield  1
    }

```
and this one:
```f#
let a = seq {
        while true do
        	yield  1
    }
```
becomes: 
```f#
let a = seq {
        while true do
    yield  1
    }

```
My config file [.emacs](https://github.com/fsharp/emacs-fsharp-mode/files/152751/emacs.txt), if it can help

**Comment by rneatherway** [comment]
@m00nlight does the SMIE indentation take effect on save as far as you know? Also, this looks like maybe `{` and `do` should be increasing the indent level but aren't?

**Comment by m00nlight** [comment]
@rneatherway  I can not re-produce the error on my local machine. Although in some cases SMIE can not indent to the right level, but it will not affect the indentation when saving the file. 

I think maybe some effect on @flypixel emacs configure file affect the format like the following snippe(which I think will untabify all the content in the current buffer when saving, maybe @flypixel can first disable such functionality and try again to see whether it will affect the format)

```elisp
;; Delete trailing whitespaces, format buffer and untabify when save buffer
(defun format-current-buffer()
    (indent-region (point-min) (point-max)))
(defun untabify-current-buffer()
    (if (not indent-tabs-mode)
            (untabify (point-min) (point-max)))
    nil)
(add-to-list 'write-file-functions 'format-current-buffer)
(add-to-list 'write-file-functions 'untabify-current-buffer)
(add-to-list 'write-file-functions 'delete-trailing-whitespace)
```

**Comment by flypixel** [comment]
Hello, @m00nlight. I have already done what you said, and switched off everything  that can make effect  on this issue. Although I found out that if to add this code in init.el:
```lisp
(setq indent-region-function '(lambda (start end &optional indent-offset)))
```
The issue is gone.

**Comment by rneatherway** [comment]
@flypixel I think maybe you didn't restart Emacs after commenting out that fragment that @m00nlight pasted. I've confirmed your behaviour with it in my .emacs, and that removing it fixes things. I also can see that your added code would 'fix' things, because it would stop your `format-current-buffer` function from doing anything.

**Comment by flypixel** [comment]
> I also can see that your added code would 'fix' things, because it would stop your format-current-buffer function from doing anything.
Yes, I know this. I use that code, because I can't find variable that disabled auto indent after saving.

**Comment by flypixel** [comment]
> @flypixel I think maybe you didn't restart Emacs after commenting out that fragment that @m00nlight pasted.

Yes, thanks. I tried it again and it works now. Thank you again
