### ISSUE TITLE
Type annotation syntax highlighting not working properly

### ISSUE THREAD

**Issue by Holtiton** [fsharp/emacs-fsharp-mode#74]
### Description

Syntax highlighting for type annotations (at least in record types) seems to work incorrectly. The regex does not terminate matching until some clause I have not figured out. You seem to be able to temporarily and randomly to fix this by re-indenting the affected lines.
### Repro steps
1. Create test .fsx file with following

```
type RecordTest1 = { something: int
                     another: string }

type RecordTest2 = { something :int; another :string }

type RecordTest3 = { something : float; another: float; third :float; }

type RecordTest4 = {
    something: int
    another: string }

type RecordTest5 =
    { something: int
      another: string }

type RecordTest6 =
    {
        something: int
        another: string
        third: Option<int>
    }

type RecordTest7 =
    {
    something: int
    another: string
    third: int option
    }
```
1. Start M-x re-builder and paste in the following  (from [fshapr-mode-font.el](https://github.com/fsharp/emacs-fsharp-mode/blob/master/fsharp-mode-font.el#L173) )

```
"[^:]:\\s-*\\(\\<[A-Za-z_'][^,)=<-]*\\)\\s-*\\(<[^>]*>\\)?"
```
### Expected behavior

This is what I got tinkering with the re-builder that seemed reasonable.
![Proper matching](https://cloud.githubusercontent.com/assets/1980127/14844648/869fb48e-0c61-11e6-9e23-feb7700ee5de.PNG)
### Actual behavior

Regex matching does not end.
![Current](https://cloud.githubusercontent.com/assets/1980127/14844653/93a6e012-0c61-11e6-93f6-5f46855a6a21.PNG)
### Known workarounds

This regex seemed to provide better results for me but I have not tested extensively as I just started using F# so I might be missing some cases.

```
"[^:]:\\s-*\\(\\<[A-Za-z0-9_']*[^ ;\n,)=<-]\\)\\(<[^>]*>\\)?"
```
### Related information
- OS version: Windows 10
- Emacs version: GNU Emacs 25.0.50.1 (x86_64-w64-mingw32) of 2015-11-10
- .NET Runtime version: 4.6.1

**Comment by rneatherway** [comment]
Closed by #76
