### ISSUE TITLE
check-project-files test fails on windows

### ISSUE THREAD

**Issue by fradav** [fsharp/emacs-fsharp-mode#80]
### Description

check-project-files test fails

### Repro steps

run the integration test

### Expected behavior

should pass

### Actual behavior

fails because of hardcoded `"/"` directory separator in the string-match, when windows encompass `"\\"`. 

### Known workarounds

replace with regexp `"\(\\\\\|/\)"`

**Comment by rneatherway** [comment]
Ah, I haven't run the integration tests on Windows for a while, because they don't pass on Appveyor due to an Emacs bug. If you have the workaround available, please do submit a PR.

**Comment by rneatherway** [comment]
Fixed by #81
