### ISSUE TITLE
Add support for project.json

### ISSUE THREAD

**Issue by kbrooks** [fsharp/emacs-fsharp-mode#90]
Is adding support for the project.json tooling format on the roadmap for this plugin?

**Comment by rneatherway** [comment]
That would need to implemented by the underlying cross-editor tooling, so not currently, no. As far as I can tell, everything is going back to using the MSBuild format in any case, so I'm not sure it's worthwhile.

**Comment by kbrooks** [comment]
That seems reasonable to me.
