### ISSUE TITLE
Wrong-type-argument stringp nil error when opening a .fsx file

### ISSUE THREAD

**Issue by kfonis** [fsharp/emacs-fsharp-mode#95]
When I try to load a .fsx file I get this error:

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  string-match("[\\"]\| " nil)
  #[257 "\301\300\"\203\302\303\304\305#\302Q\207\207" ["[\\"]\| " string-match "\"" replace-regexp-in-string "[\\"]" "\\\&"] 6 "\n\n(fn STR)"](nil)
  mapconcat(#[257 "\301\300\"\203\302\303\304\305#\302Q\207\207" ["[\\"]\| " string-match "\"" replace-regexp-in-string "[\\"]" "\\\&"] 6 "\n\n(fn STR)"](nil) " ")
  combine-and-quote-strings((nil "--nologo" "/Users/Kristian/Documents/test.fsx"))
  fsharp-mode-choose-compile-command("/Users/Kristian/Documents/test.fsx")
  fsharp-mode()
  set-auto-mode-0(fsharp-mode nil)
  set-auto-mode()
  normal-mode(t)
  after-find-file(nil t)
  find-file-noselect-1(#<buffer test.fsx> "~/Documents/test.fsx" nil nil "~/Documents/test.fsx" (6873006 16777221))
  find-file-noselect("~/Documents/test.fsx" nil nil t)
  find-file("~/Documents/test.fsx" t)
  call-interactively(find-file nil nil)
  command-execute(find-file)
- Mac OSX 10.11.5 
- Emacs 24.5

**Comment by rneatherway** [comment]
That's not a good failure mode, but it seems like you don't have F# installed. Is fsharpc on your path?

**Comment by kfonis** [comment]
I have installed F# and it's added to my path, which is why this is confusing me a lot

**Comment by rneatherway** [comment]
What is the difference between your `exec-path` variable in Emacs and your $PATH in your shell, where I assume you can run `fsharpc`?

**Comment by juergenhoetzel** [comment]
I also assume your Emacs session has a different PATH than your Bash because it's was started from a Desktop session and not from a shell. 

Could you try to start Emacs from your interactive shell?

You might also wan't to use [exec-path-from-shell](https://github.com/purcell/exec-path-from-shell) in you Emacs setup to avoid this kind of errors.

You might wan't to use

**Comment by rneatherway** [comment]
Closing as dormant.
