### ISSUE TITLE
Enhancement proposal: refactor `fsharp-mode-font`

### ISSUE THREAD

**Issue by Gastove** [fsharp/emacs-fsharp-mode#97]
### Description

I've been doing some work on `fsharp-mode-font`. My initial goal was to add syntax highlighting for a small set of F#'s rich ecosystem of operators, but my work quickly devolved in to a refactoring project. Issue #35 made me think some clean-up work in that file would not be unwelcome.

So far, all I've done is attempt to clean up the existing code, preserving existing functionality. To this end, I've done the following: 
1. Scrub out commented-out debugging/legacy code.
2. Remove the face... creation/declarations. Faces should be quite reliable on Emacs 24+.
3. Extract huge lists of constants in to variables, making the theme assignment easier to read and the variable lists easier to extend. 
4. Defined a small set of new faces. 

The good news: I think this will be considerably simpler to extend and maintain. 

More difficult: getting the tests to pass. The problem is this: if any new faces are added, or even slightly different faces assigned to a new element, the `faceup` files all need to be regenerated. Trying to regenerate `Format.fs` has turned in to a complete, and somewhat nightmareish, yak shave. The difficulty is that `Format.fs` is formatted with different whitespace configurations than my Emacs uses. Somewhere in the process of writing a `.faceup` file and running the tests, whitespace changes -- and then the tests explode not because the markup is wrong, but because whitespace no longer aligns. Thus:

```
Test fsharp-mode-face-file-test condition:
    (ert-test-failed
     ((should
       (fsharp-mode-face-test-apps "apps/FSharp.Compatibility/Format.fs"))
      :form
      (fsharp-mode-face-test-apps "apps/FSharp.Compatibility/Format.fs")
      :value nil :explanation
((on-line 107
        ("    | Nil")
        ("  | Nil"))
       (on-line 108
        ("    | Cons «k:of» 'a queue_cell")
        ("  | Cons «k:of» 'a queue_cell"))
       (on-line 179
        ("    }")
        ("  }"))
```

So.

My strong temptation is to just delete `Format.fs` from the tests.  A better solution would likely be a `.dir-locals.el` specifying how the file ought to to be formatted/behave. I'm entirely open to suggestions. My fear is: if I massage that file such that the tests pass for me, they'll likely detonate for the next person.

Relatedly: a `.dir-locals` for emacs lisp formatting could also do a world of good here. I believe I've introduced quite a set of whitespace changes as I've gone.
### Related information

I'm doing this work on Mac OSX 10.11.6, using Emacs 25.1 and Mono 4.1 installed from Homebrew. My branch is [here](https://github.com/Gastove/emacs-fsharp-mode/tree/re-fontify).

**Comment by rneatherway** [comment]
This is great, I've wanted to do this for so long. I'm just moving house, so time is a bit short, but I'll try to take a look at the `Format.fs` test. Are you sure it isn't because you have some format on save options enabled? Your PR looked like that was the case,

**Comment by Gastove** [comment]
@rneatherway yes, you're correct -- I use `ethan-whitespace-mode` to clean extraneous whitespace from files on save. In fact, my setup makes this even trickier -- I have code in my configs which font-locks keywords like `TODO`. 

I guess my point then is: it would be *awfully* nice for the tests of this repo to be as... resilient to user configurations as it's possible for them to be. I'm still getting my head around the `Makefile` and all the testing hooks, but it *looks* like the actual `test-all` functionality should be running more-or-less without any interference from my local emacs configs; writing out new `.faceup` files, on the other hand, is highly susceptible to my configs. 

...which, actually, might be an even better solution. Perhaps what we need is a `Make` target to generate new `.faceup` specs, with only `fsharp-mode` enabled? I can look in to that in my PR.

**Comment by rneatherway** [comment]
@Gastove I finally found some time to add a target to the Makefile for this. You can use `make faceup` to regenerate the `.faceup` files that have a newer F# file counterpart (or if `fsharp-mode-font.el` has changed). I think this is good as a manual step, because the tests should be checking against the expected results the user has checked in.

If that looks good to you, I'll merge it and hopefully your refactoring work can then be merged easily.

**Comment by Gastove** [comment]
@rneatherway Ah! Excellent! You're a good sight handier with Make than I am -- this was still on my "to figure out" list. 

I'm coming back to this after changing jobs -- will get the rest of the unit testing cleaned up, this merged in to my branch, and a PR open sometime soon here!

**Comment by rneatherway** [comment]
Great! I've merged that Makefile change in so you can base your work on it now.
